### ISSUE TITLE
Won't compile with RN 0.11

### ISSUE THREAD

**Issue by chetstone** [yamill/react-native-orientation#10]
When compiling Orientation.h, I get the error:

RCTOrientation/Orientation.h:16:12: Cannot find interface declaration for 'AppDelegate'

**Comment by yamill** [comment]
@watert maybe you can take a look?

**Comment by yamill** [comment]
See fix 
https://github.com/yamill/react-native-orientation/blob/master/RCTOrientation/Orientation.h

**Comment by chetstone** [comment]
Thanks. That works. Now I'm trying to use getOrientation(function(err, orientation)) and it is undefined. It does not appear to be defined in your index.js. If it doesn't exist, perhaps you could update the README to take out references to it until it does exist? Or if it does exist, perhaps I'm doing something wrong or there's another bug.

**Comment by chetstone** [comment]
I'm also getting an error from the packager: `Unable to resolve module RCTDeviceEventEmitter from .../node_modules/react-native-orientation/index.js` even though my call to `locktoportrait()` works

**Comment by gudmundurmar** [comment]
@chetstone I couldn't even get Orientation.lockToPortrait(); in componentDidMount()? Did that work for you?
Is there an issue running with 0.11 React native? Or am I doing something wrong? 
![screen shot 2015-10-01 at 6 56 05 pm](https://cloud.githubusercontent.com/assets/4741365/10235848/1e2b3f8c-686e-11e5-9c05-fd513c88dbc1.png)

**Comment by chetstone** [comment]
After this fix, yes, it works. That was the error I was getting at first, before I got the compile error. Being an Xcode dummy, I had a lot of trouble getting the .h and .m files installed as part of the project so that Xcode would actually include them in the build. 




I'm on my phone right now but as I recall, when you add the folder to the project, make sure to select "Create Groups " or something like that in the import dialog.



--

May all beings be happy!

**Comment by gudmundurmar** [comment]
Oh, great that works for me :grin: 
Sry, I snagged your thread. 
Just want to remind @yamill that you still have problems with 
1. getOrientation(function(err, orientation))
2. error from the packager: Unable to resolve module RCTDeviceEventEmitter from .../node_modules/react-native-orientation/index.js

that are here above my first comment

**Comment by jawadrehman** [comment]
@yamill can you push this fix into a new release on npm .

**Comment by yamill** [comment]
Hey guys, sorry I've been away for a while...took a long vacation!

I'm going to remove getOrientation in the next update - @watert never completed the implementation.

I'll also update the npm to reflect these changes. Will keep you posted :)
