### ISSUE TITLE
Exit app ，print error.

### ISSUE THREAD

**Issue by luoshuai5** [yamill/react-native-orientation#103]
Exit app, print error. call this "activity.unregisterReceiver(receiver)" two times, I think you can do this. 

```
 if(receiver != null) {
          activity.unregisterReceiver(receiver);
          receiver = null;
}
```
the function  onHostPause() and onHostDestroy()

**Comment by colinramsay** [comment]
I assume that this refers to:

https://github.com/yamill/react-native-orientation/blob/278291739e2b7c8ab208fdf404e4b139e24b4a3f/android/src/main/java/com/github/yamill/orientation/OrientationModule.java#L166

If `onHostPause` has already been called when `onHostDestroy` is called, the error "receiver already unregistered" will be logged. Need to verify that the code shown in the issue report would remove the need for the try/catch.

**Comment by andrerfneves** [comment]
PR #202 will fix this issue. Moving it to track on #202
