### ISSUE TITLE
react-native version in peerDependency breaks with specific react versions

### ISSUE THREAD

**Issue by dannycochran** [yamill/react-native-orientation#107]
If I install a specific, new release of React Native, e.g:

```

"dependencies": {
...
    "react-native": "git://github.com/facebook/react-native.git#v0.35.0-rc.0",
...
}
```

It does not meet the peer dependency requirement in react-native-orientation package.json. Not sure if this is caused by the rc.0 tag in the react native release. Is the peerDependency config necessary?

**Comment by andrerfneves** [comment]
v2.0.0 has RN dependency of 40+. This shouldn't occur anymore.
