### ISSUE TITLE
NativeModules.Orientation is undefined, or 'undefined is not an object (evaluating Orientation.getOrientation)'

### ISSUE THREAD

**Issue by Firfi** [yamill/react-native-orientation#109]
Hello! I'm trying to use your library but I can't get any method working, i.e. Orientation.getOrientation(). To be precise, Orientation object is required and defined in my code, but the issue is with inner getOrientation() method implementation. I've tracked it down up to `var Orientation = require('react-native').NativeModules.Orientation;` which is undefined. 

I'm running it on simulator currently.
I've installed the lib throgh npm and linked with rnpm. 
I have both RCTOrientation.xcodeproj in Libraries along with other linked libs and libRCTOrientation.a in 'Linked Frameworks and Libraries' build step (rnpm added it automatically). Also I have the necessary code (import + method declaration) in AppDelegate.m. 

I have react native 0.33.1 (it's not the last but I fancied older iOS support for my app). 

The app code: https://github.com/Firfi/yobatimer-react-native

Can you say what I'm doing wrong? 
Thanks!

**Comment by vitkrv** [comment]
Hi, @Firfi. I have same problem. Did you fix it?

**Comment by Firfi** [comment]
@vitkrv just use View onLayout

example:

```
<View onLayout={(event) => {
    this.setState(this.calculateWH(event));
}}>
```

```
calculateWH(event) {
    const l = event ? event.nativeEvent.layout : Dimensions.get('window'); // it doesn't always give the event
    return {
        vw: l.width / 100,
        vh: l.height / 100
    };
}
```

**Comment by vitkrv** [comment]
@Firfi, Thanks a lot.

Also, I'm trying to rotate window manually. But can't find properly solution.
Now I'm using `transform` style for the rotating a View. But it helps only for value `-90deg`. Have you any ides about this?

**Comment by Firfi** [comment]
@andrerfneves thank you for fixing this
