### ISSUE TITLE
Push a new version to npm

### ISSUE THREAD

**Issue by julien-rodrigues** [yamill/react-native-orientation#110]
The npm version has been updated for months!

The npm version doen't support RN >= 0.29 and I'm not really confident in adding the master branch to my package json

**Comment by rawrmaan** [comment]
@yamill  @youennPennarun Yes please!

**Comment by youennPennarun** [comment]
@rawrmaan I'm not the maintainer of this project, I can't do anything about it, sorry.

**Comment by andrerfneves** [comment]
We're working to ramp up maintenance for this project. Will work with @yamill to get RN Orientation 2.0 published to NPM as soon as possible/released. Cheers.
