### ISSUE TITLE
Required dispatch_sync to load constants for Orientation.  This may lead to deadlocks

### ISSUE THREAD

**Issue by whizkid77** [yamill/react-native-orientation#111]
I'm getting the following yellow box warning when `require`ing this module:

> Required dispatch_sync to load constants for Orientation.  This may lead to deadlocks

This did not happen until I upgraded to React Native 0.35.0.

To reproduce, just include this line anywhere in your code:
`const Orientation = require('react-native-orientation');`

It doesn't happen 100% of the time, only about 20% of the time.  It could be some race condition.

**Comment by basequatro** [comment]
Same here but only after full reload of app.

**Comment by andrerfneves** [comment]
@whizkid77 is this behavior still happening with latest version?

**Comment by whizkid77** [comment]
Sorry I don't know.  I actually haven't worked on my project for a while.  I'll post in this thread if I revisit.  Feel free to close issue.

**Comment by andrerfneves** [comment]
Cool thanks @whizkid77
