### ISSUE TITLE
Change orientation 

### ISSUE THREAD

**Issue by nanandn** [yamill/react-native-orientation#120]
Hi

I have four screens in my app. I want to change the orientation for one of the screen to landscape. In componentDidMount I call lockToLandscape(). 

But I want to restore the orientation to default when I navigate to another screen. In componentWillUnmount I call unlockAllOrientations. But the orientation is not reset. Does unlockAllOrientations revert to the default? If not, how can I revert back to the default. I could do lockToPortrait() since my original orientation is portrait. But I was wondering if there is a way to reset back to what ever the default was.

**Comment by ItsNoHax** [comment]
Well it depends how you do your routing. Imagine you have the following screens:

HomePage -> EmailList -> EmailView

If you lockToPortrait on EmailList's componentDidMount and then open EmailView, the EmailList component stays mounted which means EmailView will also be locked to portrait. 

My solution was to use a listener on the router component and then lock the portrait only when I focus on EmailList component.

In EmailList's componentDidMount:
```
    this.focusListener =  this.props.routeEmitter.addListener('didFocus', (event) => {
      if (event.component.displayName !== 'EmailList' ) {
        Orientation.unlockAllOrientations();
        return;
      }
      Orientation.lockToPortrait();
}):
```

And in the componentWillUnmount: 

```
Orientation.unlockAllOrientations();
this.focusListener.remove();
```

**Comment by colinramsay** [comment]
> Does unlockAllOrientations revert to the default?

No.

> If not, how can I revert back to the default

You'd have to store the default somewhere and force a switch to that.

This isn't really a bug and as @ItsNoHax said, you could do it from your router or some other higher-order component.
