### ISSUE TITLE
landscape mode status bar display incorrect

### ISSUE THREAD

**Issue by testxin** [yamill/react-native-orientation#123]
![image](https://cloud.githubusercontent.com/assets/5926139/20871367/069214ee-bad0-11e6-8f2e-e1a8e04e3974.png)
just use lockToLandscape function  status bar display height   but the battery doesn't show  like follow pic
![image](https://cloud.githubusercontent.com/assets/5926139/20871390/3e2ca90a-bad0-11e6-85b2-f87b31d7f511.png)

**Comment by andrerfneves** [comment]
@testxin is this still happening? What RN Version are you using?

**Comment by quinnbaetz** [comment]
I'm seeing this as well, but only on some devices.  Specifically iPhone 6s, 10.2

**Comment by quinnbaetz** [comment]
The fix I found was to put

  [application setStatusBarHidden:YES withAnimation:UIStatusBarAnimationNone];
  [application setStatusBarHidden:NO withAnimation:UIStatusBarAnimationNone];

in AppDelegate.m in didFinishLaunchingWithOptions

**Comment by andrerfneves** [comment]
This shouldn't happen with new version v2.0.0. If it persists please open a new issue. Also a workaround was provided above.
