### ISSUE TITLE
How to manually set the orientation? 

### ISSUE THREAD

**Issue by tooodooo** [yamill/react-native-orientation#124]
How to manually set the orientation? I know IOS is OK with Swift or OC, I do not know whether Android can also be?

I am using a video player , I need manually set the orientation when the vertical screen, click the full screen button to force the horizontal screen.

**Comment by saidmoya12** [comment]
That is easy!

From js code you put on event

Orientation.lockToLandscapeLeft();
Orientation.lockToLandscapeRight();

or
Orientation.lockToLandscape();

When you close fullsize 
Orientation.unlockAllOrientations();

**Comment by colinramsay** [comment]
@tooodooo please let us know if the solution @saidmoya12 provided doesn't meet your requirements and we can re-open this issue.
