### ISSUE TITLE
Installation Issue: Duplicate Symbols

### ISSUE THREAD

**Issue by robbiemoore** [yamill/react-native-orientation#129]
Hi, I'm trying to get this installed but getting the following error after I add `libRCTOrientation.a` to `Linked Frameworks and Libraries`

`duplicate symbol _OBJC_CLASS_$_Orientation in:
    /Users/Robbie/Library/Developer/Xcode/DerivedData/voiceiqoauth-cvajnuzzntoezcgiajimusldnoym/Build/Products/Debug-iphonesimulator/react-native-orientation/libreact-native-orientation.a(Orientation.o)
    /Users/Robbie/Library/Developer/Xcode/DerivedData/voiceiqoauth-cvajnuzzntoezcgiajimusldnoym/Build/Products/Debug-iphonesimulator/libRCTOrientation.a(Orientation.o)
duplicate symbol _OBJC_METACLASS_$_Orientation in:
    /Users/Robbie/Library/Developer/Xcode/DerivedData/voiceiqoauth-cvajnuzzntoezcgiajimusldnoym/Build/Products/Debug-iphonesimulator/react-native-orientation/libreact-native-orientation.a(Orientation.o)
    /Users/Robbie/Library/Developer/Xcode/DerivedData/voiceiqoauth-cvajnuzzntoezcgiajimusldnoym/Build/Products/Debug-iphonesimulator/libRCTOrientation.a(Orientation.o)
duplicate symbol _OBJC_IVAR_$_Orientation._bridge in:
    /Users/Robbie/Library/Developer/Xcode/DerivedData/voiceiqoauth-cvajnuzzntoezcgiajimusldnoym/Build/Products/Debug-iphonesimulator/react-native-orientation/libreact-native-orientation.a(Orientation.o)
    /Users/Robbie/Library/Developer/Xcode/DerivedData/voiceiqoauth-cvajnuzzntoezcgiajimusldnoym/Build/Products/Debug-iphonesimulator/libRCTOrientation.a(Orientation.o)
ld: 3 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Any insight would be appreciated.

**Comment by robbiemoore** [comment]
Solution: I added the libRCTOrientation.a inside the `RCTOrientation.xcodeproj` and that fixed it

**Comment by 8088** [comment]
I also encountered such a problem, but the solution is not the same as you.

remove libRCTOrientation.a add libreact-native-orientation.a into Build Phases.

**Comment by fungilation** [comment]
This is something broken on move from 3.1.2 to 3.1.3, if one `react-native unlink react-native-orientation` and `link` again. `libRCTOrientation.a` would be orphaned and removed from Xcode, so I need to manually link `libreact-native-orientation.a`. @stoneman1 FYI
