### ISSUE TITLE
Cannot find interface declaration for 'AppDelegate'

### ISSUE THREAD

**Issue by arunshan** [yamill/react-native-orientation#13]
[APPNAME]/node_modules/react-native-orientation/RCTOrientation/Orientation.h:16:12: Cannot find interface declaration for 'AppDelegate'

Am I missing something here? 

I followed the steps as mentioned in the README but unable to build the application because of the above error.

**Comment by arunshan** [comment]
Got that error resolved by adding the RCTOrientation folder using "Copy Bundle Resources".

**Comment by SteveAquino** [comment]
@arunshan Were you able to get this working?  When I tried as you suggested the RCTOrientation is added but there's no files in it when I look in Xcode.

**Comment by andrewljohnson** [comment]
I think this library fails if you don't name your main class AppDelegate. Like mine is called MapAppDelegate, so I get the error reported, and I can fix it by changing AppDelegate to MapAppDelegate to match my project in Orientation.h/m.

**Comment by yamill** [comment]
I'll close this. I assume the issue was resolved.

**Comment by jpcarts23** [comment]
#import "../../node_modules/react-native-orientation/iOS/RCTOrientation/Orientation.h"
