### ISSUE TITLE
你应该把最新代码同步到npm上，你git上的比npm上要新

### ISSUE THREAD

**Issue by budingts** [yamill/react-native-orientation#130]
你应该把最新代码同步到npm上，你git上的比npm上要新

**Comment by Lizhooh** [comment]
@budingts 其实作者不维护这个项目了。

**Comment by andrerfneves** [comment]
English please.

**Comment by lizhiren2016** [comment]
明明很多人都是中国人，偏要装着说英语，何必

**Comment by stoneman1** [comment]
English please and Chinese -> English translation does not work so well. But figured out it had something to do with the NPM so check other issues about that.
