### ISSUE TITLE
How to only make the specific screen support orientation?

### ISSUE THREAD

**Issue by jaggerwang** [yamill/react-native-orientation#135]
### Problem
I want to make only the video player screen of my app support orientation. But when I turned on landscape in Xcode, everything works great except that I can't disable other screens from being orientation.

### Code
The video player screen
```
...

  componentDidMount() {
    Orientation.unlockAllOrientations();
    ...
  }

  componentWillUnmount() {
    Orientation.lockToPortrait();
  }

...
```

Other screens
```
...

  componentDidMount() {
    Orientation.lockToPortrait();
    ...
  }

...
```

### ENV
react-native: 0.39
react-native-orientation: 1.17.0
iOS: 10.2 on iPhone 5s
Android: not test

**Comment by williamlk** [comment]
i have the same problem, did you have solution?

**Comment by jaggerwang** [comment]
@williamlk you can try this.

```javascript
  componentDidMount() {
    Orientation.addSpecificOrientationListener(this.orientationListener.bind(this));
    Orientation.unlockAllOrientations();
  }

  componentWillUnmount() {
    Orientation.removeOrientationListener(this.orientationListener);
    Orientation.lockToPortrait();
  }
```

In the listener you should save the current orientation, and render ui along with the current orientation.

**Comment by williamlk** [comment]
addSpecificOrientationListener() method did not invoke? Is code have any problems?
