### ISSUE TITLE
Orientation.lockToPortrait() not locking view

### ISSUE THREAD

**Issue by patricktresp** [yamill/react-native-orientation#136]
Hey,

i do want to lock certain views to portrait mode, but when calling
`Orientation.lockToPortrait();`

in any of the methods, it does not lock at all, landscape mode still changes view behaviour

i tried:
componentWillMount()
componentDidMount()

Any suggestions on that?

( the xcode Project allows "Portrait", "Landscape Left", "Landscape Right" , since i do have some views that i want to allow in landscape)

Best,

Patrick

**Comment by mickeyjc** [comment]
I have the same issue, Orientation.lockToPortrait() not locking at componentDidMount().
`Orientation.addOrientationListener(() => Orientation.lockToPortrait());` is a bit weird as it did rotate the screen then rotate it back to Landscape, not an ideal solution.

**Comment by 44326334** [comment]
@mickeyjc  I have the same issue on android. Orientation.lockToPortrait() not working at componentDidMount(), and throw a error :`undefined is not an object(evaluating ‘Orientation.lockToportrait’)`
How do I modify the Configuration in android？

**Comment by mickeyjc** [comment]
Follow the Android part of the `Configuration` section on the project README.md, it mentions to add extra two lines to the `MainActivity.java`

**Comment by 44326334** [comment]
@mickeyjc thanks your reponse . It could running that I make a mistake for no import a few pakerage on `MainActivity.java`
now，it is still the same error， but when I use  the demo of  `..\node_modules\react-native-orientation\demo\index.android.js` running , throw the same error above.

**Comment by patricktresp** [comment]
I now got it running on ios. i somehow missed the "configure" section in this. sorry about that.

**Comment by lavarajallu** [comment]
Yes I am not getting in IOS, but  fixed in android.

**Comment by soutot** [comment]
I followed the linking and configuring steps but I couldn't get it to work on iOS (didn't test in Android).
When I use toLockPortrait() or toLockLandscape() the screen starts at correct orientation, but if I rotate the device or cmd+left/cmd+right in the simulator the orientation changes, it's not really being locked.

Any suggestions?

**Comment by schlaegerz** [comment]
I was just playing with this, it appears if you add any listeners with:
Orientation.addOrientationListener

It unlocks all the orientations

**Comment by soutot** [comment]
I still couldn't get it to work. I created this repo to show a simple example of my situation: https://github.com/soutot/react-native-orientation-test

Any suggestions?

Thanks in advance

**Comment by lavarajallu** [comment]
this method call in componentWillMount

**Comment by soutot** [comment]
@lavarajallu I changed it, but it's still not locking

**Comment by lavarajallu** [comment]
I will  give on some code after 10hrs okay

**Comment by lavarajallu** [comment]
Dear Tiago Souto,

*var Orientation = require('react-native-orientation');*
* follow this  when you want change or lock to portrait*





*componentWillMount(){  if(this.props.sportName == 'Pro Football'){
Orientation.lockToLandscape();    this.setState({      HEIGHT:375,
WIDTH:667                })  }  else{   Orientation.lockToPortrait();
}  }  _orientationDidChange(orientation) {    if (orientation ==
'LANDSCAPE') {      //do something with landscape layout    } else {
Orientation.lockToLandscape();    }  }onBack(){
 Orientation.lockToPortrait();       this.setState({        open:false
})  }*

**Comment by soutot** [comment]
@lavarajallu I really appreciate your effort. I tried to run the following code and still getting the same scenario: the screen loads as landscape but when I rotate it (cmd + left), the whole content turns to portrait view.

```
componentWillMount() {
		Orientation.lockToLandscape();
	}  

	_orientationDidChange(orientation) {    
		if (orientation == 'LANDSCAPE') {
			Orientation.lockToLandscape();    
		}  
	} onBack() {
	 	Orientation.lockToPortrait();
	}
	
	render() {
		return(
			<View style={{ flex: 1, justifyContent: 'center', alignItems: 'center'}}>
				<Text>This is my content</Text>
			</View>
		);
	}
```

My package.json:
```
{
  "name": "teste",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "~15.4.1",
    "react-native": "^0.42.3",
    "react-native-orientation": "^1.17.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "~15.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
I also tried with RN 39, no success.

Here's the demo:
![Demo](https://media.giphy.com/media/3ohzdWNLisnewKgAkU/giphy.gif)

Would you mind trying to run the code from my repo? I still don't know why it doesn't work. I even tried to create new blank projects to check if I followed the correct setup steps.

https://github.com/soutot/react-native-orientation-test

Thanks in advance

**Comment by soutot** [comment]
Hey,
Thank you everyone for the help! After an observation of @ibussieresI found that there was an error of ```RCTBridgeModule.h' file not found```
I replaced it the import to this ```#import <React/RCTBridgeModule.h>``` and it seems to be working now!

Thank you very much!

**Comment by ibussieres** [comment]
Glad you got it working. You, should close the issue. Cheers !

**Comment by larryranches** [comment]
@soutot Is this still working for you? I want to actually lock to Portrait ```Orientation.lockToPortrait()``` but it's still allowing to go landscape. Is this scenario doing the same for you? If not, how did you get it to work?

Thanks!

**Comment by soutot** [comment]
@larryranches Yes, it's working fine here. After ```npm install``` I opened this file ```node_modules/react-native-orientation/iOS/Orientation.h``` and replaced the import to ```#import <React/RCTBridgeModule.h>``` since it's the new syntax of RN. After this it worked perfectly here. 
I created a repo with a simple example. Try cloning it and check if it works for you. If you have any issue, I'll try to help!
https://github.com/soutot/react-native-orientation-test

**Comment by timCF** [comment]
for me, after these fixes `Orientation.lockToLandscape()` works fine, but `Orientation.lockToPortrait()` still is not working...

**Comment by soutot** [comment]
@timCF that's odd. If landscape works portrait should works as well. I guess it might be something regarding your setup.
Try cloning my repo and setting up the lib. Check if it works for you.

**Comment by danilvalov** [comment]
@soutot 
Thank you for your solution! It works for me!

**Comment by andrerfneves** [comment]
Closing this for now as it works as expected

**Comment by tminard** [comment]
This does not work as expected. Orientation.h should be updated according to latest RN standard.

**Comment by kf729ik** [comment]
My imports in Orientation.h look like:

```
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#if __has_include(<React/RCTBridgeModule.h>)
#import <React/RCTBridgeModule.h>
#else
#import "RCTBridgeModule.h"
#endif
```

and it's still not working on IOS, but on Android is working well. Any suggestions? Thanks a lot!

**Comment by JayricMok** [comment]
@soutot I try your solution but the problem still exist

**Comment by soutot** [comment]
@JayricMok can you try running this sample, please? https://github.com/soutot/react-native-orientation-test
After the changes mentioned on readme it worked as expected.

> Make sure to have done the following:
> 
> * Replace #import Orientation.h to #import "../../node_modules/react-native-orientation/iOS/RCTOrientation/Orientation.h" in AppDelegate.m
> * Replace #import RCTBridgeModule.h to #import <React/RCTBridgeModule.h> in your node_modules/react-native-orientation/iOS/Orientation.h

Also, make sure you have followed all steps given here:
https://github.com/yamill/react-native-orientation#linking-native-dependencies
https://github.com/yamill/react-native-orientation#configuration

Let me know if it helps

**Comment by andrerfneves** [comment]
Thanks a lot for this @soutot! 

@JayricMok if there are any outstanding issues after testing @soutot's solution out that is related to this topic, let's create a new issue and move discussion there. This one has been closed a while now.

**Comment by oriharel** [comment]
Problem still exist for me too

**Comment by supermanxiacheng** [comment]
@kf729ik 
else i still  import  #import <React/RCTBridgeModule.h>
I think the if condition may be something wrong  ....

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#if __has_include(<React/RCTBridgeModule.h>)
#import <React/RCTBridgeModule.h>
#else

#import <React/RCTBridgeModule.h>
#endif

@interface Orientation : NSObject <RCTBridgeModule>
+ (void)setOrientation: (UIInterfaceOrientationMask)orientation;
+ (UIInterfaceOrientationMask)getOrientation;
@end

**Comment by hto** [comment]
@mickeyjc Thank you!

**Comment by dutchwebs** [comment]
Update your environment, it seemed like it fixed itself in a later version of RN for me. Before the update this worked also as a workaround: "Orientation.addOrientationListener(() => Orientation.lockToPortrait());"

**Comment by grantd77** [comment]
hey there, I have tried all the solutions mentioned, as I have encountered the same road blocks too, but none have helped me.

The project begins to compile but it ends up complaining further about missing files and can't get the library to build as part of the whole project, just to support orientations.

any other tips?

**Comment by Sheleya** [comment]
Still Orientation.lockToPortrait is not working. Any suggestions?

**Comment by HaseemUlHaq** [comment]
Make sure you have install Pods
`cd ios && pod install`

Use:
`Orientation.lockToLandscape()`
`Orientation.lockToPortrait()`

**In AppDelegate.m**
write before `@end`

`- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow ``*)window {`
`    while ([[UIDevice currentDevice] isGeneratingDeviceOrientationNotifications]) {`
`        [[UIDevice currentDevice] endGeneratingDeviceOrientationNotifications];`
`    }`
  
`    return [Orientation getOrientation];`
`  }`
