### ISSUE TITLE
PORTRAITUPSIDEDOWN is Not working

### ISSUE THREAD

**Issue by lavarajallu** [yamill/react-native-orientation#137]
I used this module, It is Working In All  Specifications Except PORTRAITUPSIDEDOWN.
Let me know how to fix this Find?

**Comment by derekgreenberg** [comment]
Make sure that 'Upside Down' is checked under General -> Deployment Info -> Device Orientation in Xcode.

**Comment by andrerfneves** [comment]
Closing this since it's been idle for a while. Checking the Device Orientation on XCode should resolve your issue. Willing to reopen this if anyone's got the same issue.
