### ISSUE TITLE
Update to react-native 0.40.0

### ISSUE THREAD

**Issue by balmasich** [yamill/react-native-orientation#139]
Please can you update to new react-native version?
https://github.com/facebook/react-native/releases/tag/v0.40.0

**Comment by joncursi** [comment]
I am getting the following file not found error on RN 0.40.0:

<img width="634" alt="screen shot 2017-01-09 at 12 13 05 pm" src="https://cloud.githubusercontent.com/assets/4974609/21775685/0eba523e-d665-11e6-8d95-776cf4d5af7d.png">

**Comment by schlaegerz** [comment]
I know this isn't really a good long term solution, and I don't know enough about the react build processes to do it right, but if anyone else is running into this problem and wants a quick fix, you can just remove the include line and replace it with this:

@interface Orientation : NSObject <RCTBridgeModule>
+ (void)setOrientation: (UIInterfaceOrientationMask)orientation;
+ (UIInterfaceOrientationMask)getOrientation;
@end

**Comment by kadzier** [comment]
I believe the fix for this is a simple two line alteration in the import statements, as contained in this pull request:

https://github.com/yamill/react-native-orientation/pull/146/commits/6ee0ddb90ffb4fab4f09180330ee22edb28c1bad

This is following Facebook's direction in how to update third party modules for react native 40.0.

**Comment by max-mykhailenko** [comment]
When you plan to approve one of PR about this issue?
https://github.com/yamill/react-native-orientation/pull/154
https://github.com/yamill/react-native-orientation/pull/153
https://github.com/yamill/react-native-orientation/pull/146

**Comment by jevakallio** [comment]
@yamill can I do something help you land one of these PRs?

**Comment by andrerfneves** [comment]
5a16ac8a3f96e12969d86a1dd1f6d548efc213b2 was merged. Should resolve RN 0.40 + issues.
