### ISSUE TITLE
Orientation.lockToPortrait Error

### ISSUE THREAD

**Issue by arunshan** [yamill/react-native-orientation#14]
I just posted a screenshot of the error below.
http://cl.ly/image/2G3p0C2w3l3X

I added the RCTOrientation directory to the project using Copy Bundled Resources. But when I use 

```
Orientation.lockToPortrait();
```

I get the above error.

**Comment by chrstffr** [comment]
+1

**Comment by yamill** [comment]
Did you try adding RCTOrientation with groups selected instead?

**Comment by tuneZola** [comment]
+1, I get the same thing. I have not tried with groups selected instead. The description is too vague, not sure what groups selected is referring to?

**Comment by yamill** [comment]
@tuneZola Add RCTOrientation folder from your node_modules/react-native-orientation folder. Make sure you have 'Create Groups' selected
