### ISSUE TITLE
In android returning only LANDSCAPE even my device is in portrait

### ISSUE THREAD

**Issue by swaroopa94** [yamill/react-native-orientation#140]
Hi,
I am using this module in my application.

In android the function 

  _updateOrientation(or) {
   // alert("HI")
      this.setState({ or });

  }
is always returning LANDSCAPE only even my device is in portrait mode.
Due to this I am getting so many design issues Can anyone help me in solving this.

**Comment by lavarajallu** [comment]
I didn't get your point

**Comment by andrerfneves** [comment]
@swaroopa94 could you provide more details / example / source code that we can take a look to try and determine what's going on?

**Comment by andrerfneves** [comment]
Closing this. If it's still happening please open new issue.
