### ISSUE TITLE
<anonymous ReactNativeHost> cannot be converted to Activity      

### ISSUE THREAD

**Issue by SheppardX** [yamill/react-native-orientation#141]
i get an error when i compile in android 

error: incompatible types: <anonymous ReactNativeHost> cannot be converted to Activity
            new OrientationPackage(this),

Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by ng-hai** [comment]
Change "new OrientationPackage(this)" to "new OrientationPackage()".
It works for me.

**Comment by SheppardX** [comment]
Then he says that the argumentslist is empty...

**Comment by ng-hai** [comment]
Check this step :

// The docs say this
`Implement onConfigurationChanged method (in MainActivity.java)`

// And I do this
`Implement onConfigurationChanged method (in MainApplication.java)`

**Comment by SheppardX** [comment]
ah okay ... i will try

2017-01-09 11:09 GMT+01:00 Hai Nguyen <notifications@github.com>:

**Comment by eli88p** [comment]
I have a same problem, i tried @ng-hai solution but it's not worked
my exception:
error: constructor OrientationPackage in class OrientationPackage cannot be applied to given types;
                        new OrientationPackage(this)
                              ^
  required: Activity
  found: <anonymous ReactNativeHost>
  reason: actual argument <anonymous ReactNativeHost> cannot be converted to Activity by method invocation conversion
1 error
:app:compileDebugJavaWithJavac FAILED

anybody can help me please?

**Comment by cherta** [comment]
Hi all I'm new to RN but I think I know why this is failing. [This commit](https://github.com/yamill/react-native-orientation/commit/a2d01060ca0e5aa8fe5c3dd4ad75c535bb519ec0#diff-1698f072ed1f5ada01105f9e4897f4daL18) changed the constructor but is not yet published to npm (`react-native-orientation@1.17.0`). 

If you look into your node_modules folder you see the `OrientationPackage` with the old Activity constructor. 

I think people experiencing this issue can get a temporary fix it by pointing the dependency to the `master` version of the repo until the @yamill pushes the next version to npm.

Simply point your `package.json` entry to:
```
"dependencies": {
	"react": "~15.4.0-rc.4",
	"react-native": "0.40.0",
	...
	"react-native-orientation": "git+https://git@github.com/yamill/react-native-orientation.git"
},
```

Then run `yarn` or `npm innstall` and try to re compile with `react-native run-android`. It worked for me.

**Comment by eli88p** [comment]
Thank you!  It's work!

**Comment by wellingtonblessed** [comment]
@cherta Thanks, it works

**Comment by ng-hai** [comment]
close

**Comment by zhiyong888** [comment]
I tried to change "react-native-orientation": git+https://git@github.com/yamill/react-native-orientation.git"
but still not working.../Users/luca/workspace/pillsy/android/app/src/main/java/com/pillsy/MainApplication.java:27: error: constructor OrientationPackage in class OrientationPackage cannot be applied to given types;
            new OrientationPackage(this)
            ^
  required: no arguments
  found: <anonymous ReactNativeHost>
  reason: actual and formal argument lists differ in length
1 error
:app:compileDebugJavaWithJavac FAILED

**Comment by cherta** [comment]
Hi, @zhiyong888! Try removing `node_modules` and executing `yarn` again, maybe that helps.

**Comment by zhiyong888** [comment]
Hi @cherta , I already tried to remove `node_modules` and executed `npm install`. but still not working...

**Comment by cherta** [comment]
If you check the [code on the master branch](https://github.com/yamill/react-native-orientation/blob/master/android/src/main/java/com/github/yamill/orientation/OrientationPackage.java#L15), the constructor that complains about the argument is in the correct shape. Try looking at your `node_modules` version of the same file to see if it's the same, or it's still downloading the npm published version.

**Comment by zhiyong888** [comment]
`package com.github.yamill.orientation;

import com.facebook.react.ReactPackage;
import com.facebook.react.bridge.JavaScriptModule;
import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.uimanager.ViewManager;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class OrientationPackage implements ReactPackage {

    public OrientationPackage() {
    }

    @Override
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
        return Arrays.<NativeModule>asList(
            new OrientationModule(reactContext)
        );
    }

    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
        return Arrays.asList();
    }
}`
This is OrientationPackage.java in my `node_modules`. very weird.

**Comment by cherta** [comment]
weird indeed. Try `react-native link` I don't think it helps but who knows

**Comment by zhiyong888** [comment]
I already tried `react-native link` and linked successful. but still not working...

**Comment by cherta** [comment]
Well, my friend, I'm out of ideas at this point :(

**Comment by drvidal92** [comment]
I solved the problem using all answers together:

1: `react-native start`
2: replace content of react-native-orientation with `"git+https://git@github.com/yamill/react-native-orientation.git"` in package.json 
3: `react-native upgrade`
4: `react-native link`
5: `react-native run-android` with genymotion opened

Hope it helps, this is my first answer.

**Comment by andrerfneves** [comment]
Closing this as there have been updates to `master` which fix this.

**Comment by idlework** [comment]
@andrerfneves this issue is not fixed with the npm module. yarn add / npm install still gives this issue.

**Comment by andrerfneves** [comment]
@idlework like it says in the README, the `npm` module is not updated to the GitHub repository. Which means the NPM version of the package is outdated. Please use the `"git+https://git@github.com/yamill/react-native-orientation.git"` instead of the npm version inside your package.json. You can also read through the README for more info. If error persists, please open another issue.
