### ISSUE TITLE
Orientation.lockToPortrait() throw a error

### ISSUE THREAD

**Issue by 44326334** [yamill/react-native-orientation#142]
I was write it at componentDidMount(), but it throw a red error like this:
`undefined is not an object(evaluating ‘Orientation.lockToportrait’)`

**Comment by ostigley** [comment]
I'm having a very similar issue on Android.
`Cannot read property of 'lockToLandscapeLeft' of undefined.`

```
import Orientation from 'react-native-orientation'
...
componentDidMount () {
  Orientation.lockToLandscapeLeft()
}
```

putting in a console.log on Orientation produces:
```
addOrientationListener: addOrientationListener(cb)
addSpecificOrientationListener: addSpecificOrientationListener(cb)
getInitialOrientation: getInitialOrientation()
getOrientation: getOrientation(cb)
getSpecificOrientation: getSpecificOrientation(cb)
lockToLandscape: lockToLandscape()
lockToLandscapeLeft: lockToLandscapeLeft()
lockToLandscapeRight: lockToLandscapeRight()
lockToPortrait: lockToPortrait()
removeOrientationListener: removeOrientationListener(cb)
removeSpecificOrientationListener: removeSpecificOrientationListener(cb)
unlockAllOrientations: unlockAllOrientations()
__proto__: Object
```
so the object is clearly loaded, but the function call is failing

**Comment by puresamari** [comment]
Im also having the same issue as @ostigley

**Comment by ostigley** [comment]
sup @puresamari .  I'm not sure @yamill has much free time to support this anymore.  But after doing some reading, I figured out you you can make it work with  the following:
```
var Orientation = require('react-native').NativeModules.Orientation
...
Orientation. lockToLandscapeLeft()
```

and it worked.   Winner Winner Chicken Dinner

**Comment by jiteshwadia** [comment]
Tried both options,

1. import Orientation from 'react-native-orientation';
2. As suggested by @ostigley , var Orientation = require('react-native').NativeModules.Orientation

But still gives error `undefined is not an object(evaluating ‘Orientation.lockToportrait’)`

**Comment by quangas** [comment]
You most likely don't have the latest version, when I did npm install, it didn't actually get the latest files (it downloaded the version that used OrientationPackage(this)), so I had the same error. The correct version should be OrientationPackage() in MainApplication. 

Here's what I did to fix it and get it working. 

Try to remove the react-native-orientation from your project with:

`npm remove react-native-orientation`

Then download the zip, rename it to react-native-orientation and copy/move it to your npm_modules folder. Then link it again.

`react-native link react-native-orientation`

Note you may have to remove all references of react-native-orientation from the Android project first before you can re-link it.

**Comment by danilvalov** [comment]
Just fork this repository and use `npm install yourgitlogin/react-native-orientation`. It works for me.

**Comment by andfs** [comment]
@danilvalov could you explain me why did it work?

**Comment by andrerfneves** [comment]
@andfs the current version of the React Native Orientation package in NPM is not up to date. For now, just fetch the code directly from the repo like `npm install --save react-native-orientation@git+https://github.com/yamill/react-native-orientation.git`. The current version at `master` should have `lockToPortrait()` working on Android and iOS granted native linking/installing is correct. If error persist, please open another issue with an example code for us to look at and debug.

**Comment by stagwithadream** [comment]
> var Orientation = require('react-native').NativeModules.Orientation

thanks this works perfectly.

**Comment by SaurabhVishu** [comment]
TypeError: null is not an object (evaluating 'Orientation.lockToPortrait')

Please provide me its solution
