### ISSUE TITLE
lockToX not works on iOS.

### ISSUE THREAD

**Issue by jaggerwang** [yamill/react-native-orientation#145]
### Problem

My app has a video player page, and I want to only enable orientation in this page. I tried many ways, but still can not achieve the goal. Here is my way.

1. Turn off Landscape orientation in Xcode. If not, all pages of app can be rotated.

2. In the video player page, set orientation listener and lock to the orientation according to the received event. When rotate the screen, the app do received the correct event, but call lockToX has no effect.
```javascript
  componentDidMount() {
    ...
    this.orientationListener = orientation => {
      let {setPlayerState} = this.props;
      if (orientation == 'LANDSCAPE-LEFT') {
        Orientation.lockToLandscapeLeft();
        setPlayerState({orientation: 'LANDSCAPE-LEFT'});
      } else if (orientation == 'LANDSCAPE-RIGHT') {
        Orientation.lockToLandscapeRight();
        setPlayerState({orientation: 'LANDSCAPE-RIGHT'});
      } else {
        Orientation.lockToPortrait();
        setPlayerState({orientation: 'PORTRAIT'});
      }
    };
    Orientation.addSpecificOrientationListener(this.orientationListener);
    Orientation.unlockAllOrientations();
  }

  componentWillUnmount() {
    Orientation.removeOrientationListener(this.orientationListener);
    Orientation.lockToPortrait();
  }
```

Am I doing the right way?

### Env
react-native: 0.40.0
react-native-orientation: newest from GitHub
platform: iOS simulator, Xcode 8.2.1

**Comment by soutot** [comment]
@jaggerwang were you be able to solve it?

**Comment by jaggerwang** [comment]
@soutot sorry, I'm not familiar with native iOS developing.

**Comment by andrerfneves** [comment]
@jaggerwang please refer to the update `Demo` folder which shows how to deal with the OrientationListener.

**Comment by gitlovenotwar** [comment]
@jaggerwang Have you able to solve this issue? I have too a specific page only to landscaped.

**Comment by soutot** [comment]
@gitlovenotwar I posted a solution in this issue https://github.com/yamill/react-native-orientation/issues/136#event-1153358922
Check if it works for you. My working demo repository is still in github: https://github.com/soutot/react-native-orientation-test
