### ISSUE TITLE
Modal Presentation Crash

### ISSUE THREAD

**Issue by dozel** [yamill/react-native-orientation#148]
When you lock the screen to portrait (or landscape), and you present something modally, the app crashes without any log. Does anyone know how to get around this? I tested this on iOS, not sure if it happens on Android.

**Comment by dozel** [comment]
Just tested on Android, and it runs fine. Must be an iOS issue.

**Comment by jsdario** [comment]
It is happening for me, only in debug mode.

**Comment by loehnertz** [comment]
This same error is still existent for me in v0.42.2.
We're you able to fix it in any way?

**Comment by andrerfneves** [comment]
@dozel, @loehnertz or @jsdario could you provide an example source code I could take a look?

**Comment by loehnertz** [comment]
@andrerfneves 
With your merge commit 5a16ac8 today I was able to fix a whole lot of other bugs including this one!
I might not be able to speak for the other guys but now it gave me an error like this:
```
ExceptionsManager.js:71
View was rendered with explicitly set width/height but with a 0 flexBasis.
(This might be fixed by changing flex: to flexGrow:)
```

And that indeed helped, I had a View that had `width` together with `flex`. It's fine now with `flexGrow`. No problem on Android but a big one on iOS as it seems - but that whole error has obviously nothing to do with `react-native-orientation`. I just popped up now.

@dozel & @jsdario : You might wanna try that as well (I am on v0.42.2)

Thanks @andrerfneves for this commit today and for maintaining this altogether 😊 👍

**Comment by andrerfneves** [comment]
@loehnertz 👍 glad it all works out. Let me know if you face any other issues. Closing this since bug wasn't related to package as pointed out by [comment](https://github.com/yamill/react-native-orientation/issues/148#issuecomment-302892986).
