### ISSUE TITLE
Rotation on IPad Pro, IPad Air 2 not working

### ISSUE THREAD

**Issue by balmasich** [yamill/react-native-orientation#151]

**Comment by jasongaare** [comment]
@balmasich had the same issue, checkout the answer in this thread https://forums.developer.apple.com/thread/21432

**Comment by balmasich** [comment]
@jasongaare thanks

**Comment by blairvanderhoof** [comment]
Making it fullscreen like the thread says does not work in simulator. Not getting any events fired.

**Comment by dann1609** [comment]
what is the way to do work?

**Comment by ShantiRanjanDas** [comment]
Anyone find any solution for this, I am also getting the same error.
