### ISSUE TITLE
Should we clone the project and maintain? What happened to Yamill?

### ISSUE THREAD

**Issue by chrusart** [yamill/react-native-orientation#156]
What I can see (LinkedIn) Yamill started work for Snap inc. and from that time not maintaining the project.

**Comment by dozel** [comment]
I think we should. The issues are at 56 and counting.

**Comment by cnshsliu** [comment]
Please, we should.

**Comment by dozel** [comment]
Alright, who's down to clone the project and maintain it? Not sure if I can fix all of these issues, but I'm definitely down to help.

**Comment by colinramsay** [comment]
The best way would be to get @yamill to transfer this project to a new owner or organisation because otherwise people will always continue to visit this (seemingly dead) repo.

**Comment by dozel** [comment]
@colinramsay the whole reason why this thread was started because @yamill is AWOL.

**Comment by colinramsay** [comment]
I realise that, but if we were to orchestrate a situation in which they just had to press a button to reassign ownership then they might be open to doing that. We'd be doing them a favour 😄 

At the moment they may just be ignoring notifications but not totally uncontactable.

**Comment by ibussieres** [comment]
yamill@gmail.com according to his website.

**Comment by hugohow** [comment]
+1

**Comment by colinramsay** [comment]
I'm emailing yamill now, will report back.

**Comment by colinramsay** [comment]
I'm in contact, we're just working out how to move this forward but we should have the ability to accept PRs, etc in some form over the next couple of days.

If anyone is willing to dedicate some time to help triage issues and PRs, please let me know below.

The intention is _not_ for me to become full-time owner, but I might do so temporarily while we work out where this project can live.

**Comment by ibussieres** [comment]
I'm on 0.42 and it's working.

**Comment by colinramsay** [comment]
Guys please don't derail this issue, there are plenty of others related to RN 0.42 compatibility:

https://github.com/yamill/react-native-orientation/issues/158

**Comment by wellyshen** [comment]
@ibussieres Did you use it for iOS simulator?

**Comment by ibussieres** [comment]
@wellyshen answering in #158

**Comment by dozel** [comment]
@colinramsay hey, I'm willing to be a contributor and help fix issues. Did the transfer of ownership happen?

**Comment by colinramsay** [comment]
@dozel, that's great! The transfer hasn't been done yet, I've just sent Yamill a follow-up email.

**Comment by manask88** [comment]
i'm also willing to help some here, please let us know what happens. Ideally, he just transfers ownership and there is no need to fork this project

**Comment by colinramsay** [comment]
I still haven't received a reply to my followup. Although @yamill seemed open to the idea, if he doesn't actually perform the transfer then we'll just have to settle for running a fork.

**Comment by gaboelnuevo** [comment]
npm package needs to be updated too.

**Comment by jurassix** [comment]
Why not just abandon this in favor of https://github.com/walmartlabs/react-native-orientation-listener

**Comment by colinramsay** [comment]
It doesn’t currently support the ability to lock orientations.

**Comment by rook2pawn** [comment]
> It doesn’t currently support the ability to lock orientations.

@colinramsay It does. I'm using react-native 0.42.3 in my package whilst running the github react-native cli command set (v1000) for react-native run-android / react-native start

i can lock to portrait and lock to landscape.

**Comment by colinramsay** [comment]
@rook2pawn, I was talking about `walmartlabs/react-native-orientation-listener`. It only has three API methods and none of those indicate that they can lock orientation. The documentation for it doesn't show that it's possible either.

**Comment by pess0a** [comment]
@colinramsay what about @yamill ?
some fork anywhere?

**Comment by colinramsay** [comment]
I didn't hear anything from @yamill about transferring the project, then this happened:

https://github.com/yamill/react-native-orientation/issues/162

But it seems like there haven't been any new commits since then so still nothing has happened. We have our own private fork.

**Comment by truongluong1314** [comment]
Hi @colinramsay , can you please let me know if @yamill allow you to clone the project for maintenance purpose? Thank you!

**Comment by andrerfneves** [comment]
Maintainers are in and we're starting the ramp up on the package. Bear with us.
