### ISSUE TITLE
Compilation error on demo project

### ISSUE THREAD

**Issue by joeyzhao0113** [yamill/react-native-orientation#161]
I cloned this repo and tried to launch the demo project but got below error:

```
MainActivity.java:42: error: constructor OrientationPackage in class OrientationPackage cannot be applied to given types;
            new OrientationPackage(this)
            ^
  required: no arguments
  found: MainActivity
  reason: actual and formal argument lists differ in length
1 error
```

it seems like an compilation error. 

My react-native version is `0.27.2`

**Comment by lifuzu** [comment]
+1

**Comment by engin145** [comment]
use in package.json `"react-native-orientation": "git+https://git@github.com/yamill/react-native-orientation.git",`

**Comment by joeyzhao0113** [comment]
I tried to change it in package.json file and run `npm install`. But still got the same error when run `react-native run-android`.

**Comment by jenkynolasco11** [comment]
Same here. Followed the instructions automatically and manually, and I'm getting the same error: 

```
C:\Users\jenky\Desktop\Dev\eCards\app\android\app\src\main\java\com\app\MainApplication.java:28: error: constructor OrientationPackage in class OrientationPackage cannot be applied to given types;
          new OrientationPackage()
          ^
  required: Activity
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by jenkynolasco11** [comment]
So, I solved my problem by copying the files directly from the repository. 

If you guys copied the files via npm or any other package manager, do what I did and everything will compile fine.

**Comment by joeyzhao0113** [comment]
@jenkynolasco11 Could you let me know what files did you copy to and from? Thanks.

**Comment by jenkynolasco11** [comment]
@joeyzhao0113 I copied this whole repo into my node_modules and it worked perfectly. The version of RN I'm using is ``0.42``.

**Comment by joeyzhao0113** [comment]
I just tried but still the same error. Why doesn't `npm install` work?

**Comment by nhuthan** [comment]
same error

**Comment by neilzhengzx** [comment]
same error

**Comment by zhaoyi0113** [comment]
It seems that this project is not working with the latest version of react-native.

**Comment by loehnertz** [comment]
Removing the whole directory in 'npm_modules' adding the Git-Version to package.json and then doing 'npm install' again fixed it for me without a problem!

**Comment by aqnaruto** [comment]
@zhaoyi0113 same issue ,do you figure it out?

**Comment by aqnaruto** [comment]
@jenkynolasco11 are you sure current react-native-orientation is work?

i saw this file 's construct method is still different from in MainApplication 's call method

> https://github.com/yamill/react-native-orientation/blob/master/android/src/main/java/com/github/yamill/orientation/OrientationModule.java

**Comment by andrerfneves** [comment]
We're in the midst of updating and ramping up development in this project. Hoping these incoming fixes will resolve the outstanding issues in this thread.

**Comment by aqnaruto** [comment]
thank you ,it is surpport rn>4.2 ,right?

**Comment by andrerfneves** [comment]
@aqnaruto yes, the package does work with RN 0.40+. Check 5a16ac8a3f96e12969d86a1dd1f6d548efc213b2 commit to see the changes.

**Comment by aqnaruto** [comment]
thank you ,nice work!  handsome!@andrerfneves
