### ISSUE TITLE
cocoapods + swift

### ISSUE THREAD

**Issue by navratill** [yamill/react-native-orientation#163]
Hello, 

when I am installing react-native-orientation with cocoapods (I am using use_frameworks!) into swift project, there I can't use it. 

Is there some way how to make it work? When I have "import react_native_orientation" it says "Could not build Objective-c module" because RCTBridgeModule in Orientation.h is not found (React is also as a cocoapod dependency)

Thank you

**Comment by navratill** [comment]
okay, this PRs are solving it(linked down): https://github.com/yamill/react-native-orientation/issues/139 

when it will be merged?

**Comment by cxjpxl** [comment]
requrie is ok

**Comment by andrerfneves** [comment]
@navratill We've removed cocoapods support. Please follow updated README instructions
