### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by aqnaruto** [yamill/react-native-orientation#166]
![image](https://cloud.githubusercontent.com/assets/9067159/25197276/1d4ae812-2576-11e7-83c7-3ca68807a6d9.png)
see this picture ,you changed construt method,but , there is no parameter in mainApplication

**Comment by aqnaruto** [comment]
i changed version into  1.70,but
![image](https://cloud.githubusercontent.com/assets/9067159/25214781/eb5fc77c-25cb-11e7-9cdf-0eb73c15f217.png)

**Comment by chenyin8888** [comment]
mark

**Comment by aqnaruto** [comment]
i solved my problem，and forked and writed solution,https://github.com/aqnaruto/react-native-orientation/blob/master/README.md
