### ISSUE TITLE
In iOS if I turn auto rotate to on then my entire app is rotating even I restricted to portrait

### ISSUE THREAD

**Issue by swaroopa94** [yamill/react-native-orientation#167]
Hi,

For my app I allowed only portrait mode in xcode.
But when I adding the following code in appdelegatre.m file then when I turn my devie to landscape then my app also is rotating in landscape mode only.
```
 - (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
    return [Orientation getOrientation];
  }
```

If I remove the line then its in portarit only but the Orientation.lockToLandscape() is not supporting 
Can you tell how to solve this.

Thanks

**Comment by andrerfneves** [comment]
This package effectively takes over the basic setup done on XCode. Please check the updated guide on README and use v2.0.0.
