### ISSUE TITLE
Why Bluetooth permission?

### ISSUE THREAD

**Issue by sospedra** [yamill/react-native-orientation#173]
Exactly here: https://github.com/yamill/react-native-orientation/blob/278291739e2b7c8ab208fdf404e4b139e24b4a3f/android/src/main/AndroidManifest.xml#L4

I cannot see where is this being used

**Comment by andrerfneves** [comment]
PR #138 is being reviewed and should resolve this issue.

**Comment by sospedra** [comment]
Cool
