### ISSUE TITLE
React/RCTBridgeModule.h file not found

### ISSUE THREAD

**Issue by sergio-solnet** [yamill/react-native-orientation#177]
Pointing to the master branch, but Xcode project fails to build.

<img width="695" alt="screenshot at may 29 21-02-59" src="https://cloud.githubusercontent.com/assets/26699244/26543625/c2155264-44b2-11e7-94ec-f78926673c37.png">

The same error occurs with React/RCTEventDispatcher.h in Orientation.m file

Any ideas how it can be fixed?

**Comment by andrerfneves** [comment]
@sergio-solnet what RN version are using? Did you follow the updates instructions on README?

**Comment by stoneman1** [comment]
Seems like old version of RN. Try the new master. ifdef was replaced with if

**Comment by Stefan-vs** [comment]
I've got the same problem with a project running react-native 0.39.2

**Comment by stoneman1** [comment]
@Stefan-vs newest master? New master should not have that ifdef there it should only be if

**Comment by Stefan-vs** [comment]
@stoneman1 yes
<img width="335" alt="screen shot 2017-06-08 at 22 11 19" src="https://user-images.githubusercontent.com/17435135/26948673-8063f69e-4c97-11e7-86a1-03d6e0c5d439.png">

**Comment by stoneman1** [comment]
Will check today / tomorrow this

**Comment by stoneman1** [comment]
https://github.com/yamill/react-native-orientation/commit/01feaaaeadc62d02d26adbdf4633c3c92c88429c broke this. Will patch today

**Comment by andrerfneves** [comment]
@Stefan-vs please check with the updated version of `master`

**Comment by Stefan-vs** [comment]
It's working!
