### ISSUE TITLE
Orientation change without supportedInterfaceOrientationsForWindow

### ISSUE THREAD

**Issue by rogerkerse** [yamill/react-native-orientation#178]
Is there a way to get device orientation without overriding what I have set in plist. Kind of like a virtual vs actual?

**Comment by airman00** [comment]
Possibly react-native-orientation is what you're looking for?

You'll need to modify your NavigationApplication.java and add on onConfigurationChanged in there, like I did here:
https://github.com/airman00/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/NavigationApplication.java

**Comment by andrerfneves** [comment]
@rogerkerse I don't believe this is possible with this package. If you find a workaround please let us know of your solution. Cheers.
