### ISSUE TITLE
NPM Deployment

### ISSUE THREAD

**Issue by andrerfneves** [yamill/react-native-orientation#183]
@stoneman1, should we deploy to NPM under a different name to stop this confusion between pointing to `master` branch? @yamill doesn't seem to be active at all in GitHub and I doubt we'd be able to have him move the `react-native-orientation` npm package to one of us. What are your thoughts? We could do `react-native-device-orientation` or something along those lines, but then the name will differ from the GitHub package name.

**Comment by stoneman1** [comment]
I think we should ask @yamill to allow us to do updates on npm. If nothing happens next week perhaps we have to make a new npm package.

**Comment by andrerfneves** [comment]
@stoneman1 cool that sounds like a plan.
@yamill, what are your thoughts? Any chance you can hook us up with access to do NPM updates? Should be a quick 5 second thing really.

**Comment by abhishiv** [comment]
@stoneman1 Please publish a new npm package if you can.

**Comment by stoneman1** [comment]
Seems like we can't catch @yamill, so let's do our own npm package?  We probably should fork this into a new repo then to match it with the package name?

**Comment by andrerfneves** [comment]
@stoneman1 I guess we could write that up in the README file. What name are you thinking? `react-native-orient` & `react-native-orientation` & `react-native-orientation-controller` are all taken.

**Comment by stoneman1** [comment]
Why is there so many packages? :(

**Comment by andrerfneves** [comment]
I'm about to get `react-native-device-orientation`. That's the best one so far.

**Comment by stoneman1** [comment]
It is taken already :(

**Comment by stoneman1** [comment]
Maybe I try to email @yamill ?

**Comment by andrerfneves** [comment]
Ah damn. Yamill doesn't seem to be repsonsive or interested in dealing with this Open Source stuff. I'm guessing he's also got some issues with doing OSS while working for SnapChat.

**Comment by andrerfneves** [comment]
`react-native-orientation-handler`? lol
`react-native-orientation-package`? lol

**Comment by stoneman1** [comment]
Not good names :D

**Comment by andrerfneves** [comment]
Yeah I know. Just thinking of anything at this point.

**Comment by stoneman1** [comment]
Sent @yamill a email and explaining the situation.

**Comment by andrerfneves** [comment]
Alright cool. Sounds good.

**Comment by Gaia-Nutrition** [comment]
Any updates? Would really love to import this properly :)

**Comment by stoneman1** [comment]
@andrerfneves Maybe we fork it and use name react-native-orientation2?

**Comment by yamill** [comment]
Hi, I can give access to the npm. Can you list the usernames who need access? Thanks!

**Comment by yamill** [comment]
Just gave access to @stoneman1 and @andrerfneves

**Comment by andrerfneves** [comment]
@yamill thank you for the access. We should now be good to move along with our deployment. A release will be made. Be in the lookout for it on an updated README. @stoneman1 I can probably branch a release tomorrow. Closing this for now.
