### ISSUE TITLE
autoRotation (w/ fixed parent)

### ISSUE THREAD

**Issue by brianjd** [yamill/react-native-orientation#19]
Feels like I am missing something obvious, but does anyone know of a workaround to keep the parent window/view fixed, while allowing specific children to autorotate?

**Comment by ajoshdee** [comment]
+1

**Comment by andrerfneves** [comment]
This package doesn't allow for this. As the README states, we can designate orientation on a `per screen basis`. PRs are welcome. Closing this for now.
