### ISSUE TITLE
Android installation error

### ISSUE THREAD

**Issue by AndrewMigal** [yamill/react-native-orientation#191]
Hi. I get this errors. 
`MainActivity.java:26: error: cannot find symbol
          public void onConfigurationChanged(Configuration newConfig) {
                                             ^
  symbol:   class Configuration
  location: class MainActivity
MainActivity.java:28: error: cannot find symbol
            Intent intent = new Intent("onConfigurationChanged");
            ^
  symbol:   class Intent
  location: class MainActivity
MainActivity.java:28: error: cannot find symbol
            Intent intent = new Intent("onConfigurationChanged");
                                ^
  symbol:   class Intent
  location: class MainActivity
3 errors
:app:compileDebugJavaWithJavac FAILED
`

**Comment by andrerfneves** [comment]
@AndrewMigal did you follow the steps below, present in the [README](https://github.com/yamill/react-native-orientation/blob/master/README.md) file for the package?

<img width="925" alt="screen shot 2017-06-22 at 4 53 06 pm" src="https://user-images.githubusercontent.com/2574011/27455461-5919503c-576b-11e7-83db-bba48c1e947f.png">

Are you sure you have imported Intent and Configuration? Also, just to make sure, are you using the npm version of this package or is your package pointed to `master` branch on this GitHub repository?

**Comment by AndrewMigal** [comment]
@andrerfneves That's it. My fault, sorry!
