### ISSUE TITLE
Error while building android with 

### ISSUE THREAD

**Issue by karan101292** [yamill/react-native-orientation#192]
Take a look at following error. It occurs when I run `react-native run-android`. 
I have configured everything mentioned in documentation. 
My react-native version is RN 0.44

```
error: constructor OrientationPackage in class OrientationPackage cannot be applied to given types;
          new OrientationPackage()
          ^
  required: Activity
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
```

**Comment by karan101292** [comment]
got it worked with #93

**Comment by andrerfneves** [comment]
@karan101292 Seems like you got it working. Going to close this then!
