### ISSUE TITLE
getSpecificOrientation is not a function in latest master

### ISSUE THREAD

**Issue by inferusvv** [yamill/react-native-orientation#195]
I've installed latest master and seems like something wrong with `getSpecificOrientation`. I seen PR where it is bridged, but it is not working for me

**Comment by andrerfneves** [comment]
@inferusvv is this happening on iOS or Android?

**Comment by inferusvv** [comment]
Android. I see, that functionality was reverted in some reasons

**Comment by PimDeWitte** [comment]
Same here.

**Comment by andrerfneves** [comment]
@inferusvv & @PimDeWitte, `getSpecificOrientation` is not a method implemented in the Android side of things. Currently only works in iOS. Will make a note to add a blurb about this to the README. PR's for this functionality are welcome.

**Comment by inferusvv** [comment]
@andrerfneves Could you tell please why implemented functionality was reverted?

**Comment by andrerfneves** [comment]
@inferusvv I'm not aware of why the code was reverted. I'm guessing it didn't work as intended after merged. If you would like to read upon that PR/code and bring back the functionality for Android we can open a new PR for it.
