### ISSUE TITLE
lockToLandscape() applies landscape mode for the previous screen

### ISSUE THREAD

**Issue by valerybodak** [yamill/react-native-orientation#196]
I have component **A** which I set to portrait mode:

```
class A extends Component {   
    ...
    componentDidMount(){
        Orientation.lockToPortrait();
    }
}
```

I press some button and open component **B** which I set to landscape mode:

```
class B extends Component{
    ...
    componentDidMount(){
        Orientation.lockToLandscape();
    }
}
```
When I press hardware BACK button on **Android** I see component **A** in the landscape mode.

Any suggestions? Please help me.

**Comment by andrerfneves** [comment]
@valerybodak I dealt with that in one of my applications too, my workaround was to have a `Orientation.lockToPortrait()` call running together with my `navigator.pop()` call so that I force the Portrait orientation when routing back to my previous screen.

**Comment by valerybodak** [comment]
@andrerfneves 
Yes. it works for Android. Thank you.

**Comment by andrerfneves** [comment]
Glad it worked. Closing this as there is a known workaround.
