### ISSUE TITLE
error when the device is left  on a flat surface

### ISSUE THREAD

**Issue by manask88** [yamill/react-native-orientation#20]
when the device is left on a flat surface, its reporting unknown as orienation

**Comment by yamill** [comment]
the api will allow you to detect unknown :)

**Comment by manask88** [comment]
but that doesnt sound right, shouldnt it be portrait or landscape?

**Comment by yamill** [comment]
it's not detecting either?

**Comment by manask88** [comment]
i dont get portrait or landscape. What it returns is unknown, which makes
it feel like a bug

On Wed, Dec 2, 2015 at 11:17 AM, Yamill Vallecillo <notifications@github.com
