### ISSUE TITLE
No podspec found in 2.0.0

### ISSUE THREAD

**Issue by DriesVS** [yamill/react-native-orientation#203]
I was wondering why the podspec/gradle files got removed in the 2.0.0?
Currently we only use cocoapods/gradle for all our react native dependencies, we like to keep it that way.

Is there a reason for this change?

Thx!

**Comment by andrerfneves** [comment]
@DriesVS given inconsistencies between the `cocoapods/rnpm` ecosystems we decided to follow the general pattern that most RN-packages are following by using `react-native link` instead. I can however bring that functionality back if it's a requirement for you. I imagined most users didn't use it given no `cocoapods` documentation/guide for this package.

Stay on v1.1.17 for now and I'll try and merge a PR in today or early tomorrow so you can update to v2.0.0. Sorry about the confusion.

**Comment by bd-arc** [comment]
Hi @andrerfneves,

I confirm that we would be really glad to see the podspec and gradle files come back ;)

**Comment by andrerfneves** [comment]
@bd-arc @DriesVS I'll be able to work on this tomorrow. I've been busy attending the Chain React Conference. Will try and get a PR and a release up tomorrow.

**Comment by andrerfneves** [comment]
@bd-arc and @DriesVS could you try `v2.1.0`? Just published to NPM. I've tried on a brand new RN install and it worked, but want to make sure it works on a project already using Pods.

**Comment by andrerfneves** [comment]
#209

**Comment by DriesVS** [comment]
@andrerfneves I can confirm that react-native-orientation v2.1 works on existing projects using Cocoapods! Thanks for bringing back the Podspec guys!!

**Comment by andrerfneves** [comment]
Perfect. Closing this then.
