### ISSUE TITLE
[Android] Rotating screens makes app restart to initial scrren

### ISSUE THREAD

**Issue by itswaze** [yamill/react-native-orientation#206]
Hi!

I have a modal that shows a swiper with images, and It has landscape support. But on Android, everytime I rotate the screen the app resets to main screen. Although on iOS it works perfectly fine.

Anyone experienced this?

EDIT: More detailed explanation and videos: https://github.com/facebook/react-native/issues/14971

**Comment by hbk671104** [comment]
Same. Any update on this?

**Comment by itswaze** [comment]
I found out what was doing that to mine. It was the splash screen. Really weird!
I started the project from the beginning and started adding all the components one at a time, till I found out that it was the splash screen doing that.

So I removed it and now it won't crash. I have to find out another solution for the splash screen.
It's a really weird bug, but that was it on my end.

**Comment by andrerfneves** [comment]
What splash screen were you using @itswaze?

**Comment by itswaze** [comment]
I used the normal splash screen, natively, on Android Studio. So it's strange that the app resets...
But i'll try a splash screen library and maybe it won't reset that way.

**Comment by andrerfneves** [comment]
@itswaze I believe Android apps are actually not meant to have a splash screen, at least not like iOS apps do. But maybe give `react-native-smart-splash-screen` a try. I have used it along with this package in the past and it works just fine. 

@hbk671104 are you still having issues with the above?

**Comment by samw2k00** [comment]
@andrerfneves  im having similar issue with this, when i have `Orientation.unlockAllOrientations()` on one of my screen (react-native-navigation), when i rotate the screen, the app restarted, sometime it crashed.

**Comment by andrerfneves** [comment]
@samw2k00 could you check if this solves it? https://github.com/wix/react-native-navigation/issues/661.

**Comment by samw2k00** [comment]
@andrerfneves I decided to get rip of the android splash screen and implement the smart splash screen. That work

**Comment by andrerfneves** [comment]
Awesome @samw2k00!

@itswaze I'm gonna go ahead and closing this as the issue doesn't seem to be related to this package. Open a new one if you believe it is.
