### ISSUE TITLE
Specific Orientation not available on Android

### ISSUE THREAD

**Issue by facuescobar** [yamill/react-native-orientation#207]
Hi, 

```
getSpecificOrientation(),
addSpecificOrientationListener(),
removeSpecificOrientationListener(),
```

This functions are not available on Android.
 Seems there was an old PR to handle this, but it was reverted.

https://github.com/yamill/react-native-orientation/pull/51

It would be great to have this feature working on Android!
Thanks!

**Comment by stoneman1** [comment]
Hi,

Do you have time to make a new PR against the new master? Not sure when I have time to do one (Will be away at least this weekend). Will then test and merge :)

**Comment by andrerfneves** [comment]
@facuescobar until a PR is created against `master` addressing this, we can add a notice to the absence of these methods on Android platforms. It's important to note that the PR was reverted given certain issues, so the new implementation on Android would have to take that into account. Closing this for now.
