### ISSUE TITLE
Incorrect podspec.

### ISSUE THREAD

**Issue by powerscin** [yamill/react-native-orientation#216]
On pod install step caught error:
```fatal: Remote branch 2.1.0 not found in upstream origin```
You might create 2.1.0 tag

**Comment by stoneman1** [comment]
Made a release. Does it work now?

**Comment by powerscin** [comment]
No.
Sorry, looks like I deceived you. Could you create 2.1.0 branch?

**Comment by stoneman1** [comment]
Ah checked the podspec file and it seems to want 2.1.0 tag instead of v2.1.0. @andrerfneves Do we want to change podspec or the names of the releases?

**Comment by stoneman1** [comment]
Should work now. Lets see where we end up on those releases.

**Comment by powerscin** [comment]
Yes, now it works. Thanks a lot

**Comment by andrerfneves** [comment]
@stoneman1 we can just use v.2.x.x for the `name` of the release and actually `tag` the release with 2.x.x from now on. Thanks for handling this.
