### ISSUE TITLE
Bug: undefined is not an object (evaluating 'Orientation.lockToPortrait')

### ISSUE THREAD

**Issue by Shudrum** [yamill/react-native-orientation#218]
Hello!

I'm trying to lock my application orientation. And I have some problems…

Here are the steps I've followed as I don't wan't to `eject` my application:

First, install…

```
$ npm install react-native-orientation --save
mobile@0.1.0 /Users/shudrum/www/Shudrum/mobile
└── react-native-orientation@2.1.0 

npm WARN lottie-react-native@1.1.1 requires a peer of react@>=15.3.1 but none was installed.
npm WARN react-native-branch@2.0.0-beta.3 requires a peer of react@>=15.4.0 but none was installed.
$
```

Then the link:

```
$ react-native link react-native-orientation
Scanning 718 folders for symlinks in /Users/shudrum/www/Shudrum/mobile/node_modules (5ms)
$
```

Finally, here is the simple usage:

```js
import React, { Component } from 'react';
import Orientation from 'react-native-orientation';
import { StyleSheet, View, ScrollView } from 'react-native';
import PageLogin from './Page/Login';

export default class MyApp extends Component {
  componentWillMount() {
    Orientation.lockToPortrait();
  }
  render() {
    return (
      <View>
        <ScrollView scrollEnabled={false} contentContainerStyle={style.scroll}>
          <PageLogin />
        </ScrollView>
      </View>
    );
  }
}
```

And nope … I still get this error:
**undefined is not an object (evaluating 'Orientation.lockToPortrait')**

This is the first time I link a package, maybe the link have failed?

For more information:

- Node version: 8.1.2
- Npm version: 4.6.1 (as we still cannot use the v5 for the CLI)
- React Native CLI version : 0.46.4

If I can help, I will!

Thank you!

And finally the complete (useless?) stack:

```
undefined is not an object (evaluating 'Orientation.lockToPortrait')

lockToPortrait
    index.js:39:16
componentWillMount
    App.js:8:4
measureLifeCyclePerf
    ReactNativeStack-dev.js:1625:15
mountComponent
    ReactNativeStack-dev.js:1666:57
mountComponent
    ReactNativeStack-dev.js:1331:53
mountChildren
    ReactNativeStack-dev.js:2831:62
initializeChildren
    ReactNativeStack-dev.js:2900:45
mountComponent
    ReactNativeStack-dev.js:2929:84
mountComponent
    ReactNativeStack-dev.js:1331:53
performInitialMount
    ReactNativeStack-dev.js:1718:54
mountComponent
    ReactNativeStack-dev.js:1670:184
mountComponent
    ReactNativeStack-dev.js:1331:53
performInitialMount
    ReactNativeStack-dev.js:1718:54
mountComponent
    ReactNativeStack-dev.js:1670:184
mountComponent
    ReactNativeStack-dev.js:1331:53
performInitialMount
    ReactNativeStack-dev.js:1718:54
mountComponent
    ReactNativeStack-dev.js:1670:184
mountComponent
    ReactNativeStack-dev.js:1331:53
mountChildren
    ReactNativeStack-dev.js:2831:62
initializeChildren
    ReactNativeStack-dev.js:2900:45
mountComponent
    ReactNativeStack-dev.js:2929:84
mountComponent
    ReactNativeStack-dev.js:1331:53
performInitialMount
    ReactNativeStack-dev.js:1718:54
mountComponent
    ReactNativeStack-dev.js:1670:184
mountComponent
    ReactNativeStack-dev.js:1331:53
performInitialMount
    ReactNativeStack-dev.js:1718:54
mountComponent
    ReactNativeStack-dev.js:1670:184
mountComponent
    ReactNativeStack-dev.js:1331:53
performInitialMount
    ReactNativeStack-dev.js:1718:54
mountComponent
    ReactNativeStack-dev.js:1670:184
mountComponent
    ReactNativeStack-dev.js:1331:53
mountChildren
    ReactNativeStack-dev.js:2831:62
initializeChildren
    ReactNativeStack-dev.js:2900:45
mountComponent
    ReactNativeStack-dev.js:2929:84
mountComponent
    ReactNativeStack-dev.js:1331:53
performInitialMount
    ReactNativeStack-dev.js:1718:54
mountComponent
    ReactNativeStack-dev.js:1670:184
mountComponent
    ReactNativeStack-dev.js:1331:53
mountChildren
    ReactNativeStack-dev.js:2831:62
initializeChildren
    ReactNativeStack-dev.js:2900:45
mountComponent
    ReactNativeStack-dev.js:2929:84
mountComponent
    ReactNativeStack-dev.js:1331:53
performInitialMount
    ReactNativeStack-dev.js:1718:54
mountComponent
    ReactNativeStack-dev.js:1670:184
mountComponent
    ReactNativeStack-dev.js:1331:53
performInitialMount
    ReactNativeStack-dev.js:1718:54
mountComponent
    ReactNativeStack-dev.js:1670:184
mountComponent
    ReactNativeStack-dev.js:1331:53
performInitialMount
    ReactNativeStack-dev.js:1718:54
mountComponent
    ReactNativeStack-dev.js:1670:184
mountComponent
    ReactNativeStack-dev.js:1331:53
mountComponentIntoNode
    ReactNativeStack-dev.js:2027:50
perform
    ReactNativeStack-dev.js:1391:99
batchedMountComponentIntoNode
    ReactNativeStack-dev.js:2033:24
perform
    ReactNativeStack-dev.js:1391:99
renderComponent
    ReactNativeStack-dev.js:2061:45
renderApplication
    renderApplication.js:34:4
runApplication
    AppRegistry.js:183:26
__callFunction
    MessageQueue.js:260:47
<unknown>
    MessageQueue.js:101:26
__guard
    MessageQueue.js:228:6
callFunctionReturnFlushedQueue
    MessageQueue.js:100:17
```

**Comment by andrerfneves** [comment]
@Shudrum Did you follow all the instructions to configure the Orientation module from the README file? Also, what do you mean by `eject` your application? Are you using CRNA?

**Comment by Shudrum** [comment]
Hi @andrerfneves!

Exactly, I am using CRNA, so I cannot link the dependency manually, only automatically. This is what I mean by `eject`: `react-native eject`.

**Comment by vccabral** [comment]
I am getting the same issue with a new project. Any ideas of where to start looking? I am use to the old style react-native project that has an ios folder which seem to be gone now.

**Comment by Shudrum** [comment]
Maybe related to that: https://github.com/rebeccahughes/react-native-device-info/issues/181

**Comment by andrerfneves** [comment]
@Shudrum I haven't built React Native applications using CRNA. It's great for small prototypes and all but when dealing with a large application I like to be in control of all of the aspects of my application. That being said, I don't believe you can use native-modules with CRNA. It uses Expo's SDK and to allow for use with this package you'd need to eject it. Read more on @skevy's answer here: https://github.com/airbnb/native-navigation/issues/49#issuecomment-286900613

**Comment by Ajith-Pandian** [comment]
@Shudrum If you want to add Native modules you need to eject your app. It's documented in create react native app under Philosophy->**_No Lock-In: You can always "eject" to your own build setup if you need to write custom native code or modify how your app is built._**

**Comment by ebarns** [comment]
I've also been having this issue and i used the regular react native init. No need to eject my app. I've followed the readme directions many times. Always undefined

**Comment by andrerfneves** [comment]
@ebarns can you show us some reproduction code that I can test with? What version of RN? Maybe create a repo that I can check it out! Thanks

**Comment by ebarns** [comment]
@andrerfneves I'm using RN 0.46.4
I'll work on setting up a repo soon. Thanks.

**Comment by ndejesus1227** [comment]
Just commenting that I'm seeing the same error. What's crazy to me is that when you `console.log(Orientation)` you can clearly see all of the functions that come with it. However, calling them makes Orientation undefined? 

Madness!

I also installed with RN init and I only ran npm link, didn't do it manually.

**Comment by ndejesus1227** [comment]
Just tried manually linking and it still doesn't work.

**Comment by andrerfneves** [comment]
@ndejesus1227 what RN version are you working with?

**Comment by ndejesus1227** [comment]
@andrerfneves react-native: 0.44.2

**Comment by andrerfneves** [comment]
And what version of `react-native-orientation`? You should be using v2.1.0 since v3.0.0 has breaking changes only meant to support latest RN version v0.47+

**Comment by ferminmoli** [comment]
I'm using react-native 0.45.1 and if I inspect NativeModules object Orientation class is not present.

**Comment by ferminmoli** [comment]
![a](https://user-images.githubusercontent.com/10004370/29878252-61b59af0-8d78-11e7-92ba-da584d8e8000.png)


You can see there that Orientation is not present, that's why the plugin is breaking.

**Comment by Solitaryo** [comment]
So? no solution or workaround for this?

**Comment by andrerfneves** [comment]
I need to be able to see code to make sure you are integrating the library correctly. Without reproducible code it is hard to know if this even is a problem / how to resolve it.

**Comment by Saad-Bashar** [comment]
For me the problem was after I changed the config in XCode, I did not rebuild from Xcode again. After rebuilding, it is working fine.

**Comment by PerspectivesLab** [comment]
same problem here with react native 0.50.3 ....

**Comment by stoneman1** [comment]
So can this be closed?

**Comment by kdenz** [comment]
Still not solved here, I've tried pretty much everything mentioned on the internet related to this issue. I'm on RN 0.43.1, I've even tried using 2.1 version as mentioned by someone that 3.x.x doesn't support < 0.47 versions well.

**Comment by stoneman1** [comment]
@kdenz any code anywhere?

**Comment by kdenz** [comment]
@stoneman1 I've given up and used react-native-orientation-locker instead lol
It allows pod install, and which works on my build when it's not npm linked .

**Comment by PerspectivesLab** [comment]
so at first i was having this error, and Orientation wasnt defined, i figured on Android i didnt instantiate the package at the right place, i was instantiating it in the application android class derived from ReactApplication,

and then i switched and instantiate it in in the main activity instead, and it worked

```
        mReactRootView = new ReactRootView(this);

        mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModulePath("index.android")
                .addPackage(new MainReactPackage())
                .addPackage( new OrientationPackage() ) 
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
        mReactRootView.startReactApplication(mReactInstanceManager, "AwesomeReactApp", null);
```

**Comment by LHJ-K2S** [comment]
this troubled for a whole day. 
when i run app with xCode ,that's ok, but error by `react-native run-ios`.
finally i rePull my whole app code from git, and run `npm install`,and install this pod, done!
