### ISSUE TITLE
react native 0.47 build error 

### ISSUE THREAD

**Issue by Lizhooh** [yamill/react-native-orientation#221]
In the previous version of RN (0.45), there was no error, but I could not install it when I upgraded to 0.47. 

(android)
```js
test\node_modules\react-native-orientation\android\src\main\java\com\github\yamill\orientation\OrientationPackage.java:25:
Error: method does not overwrite or implement super
Type method
@Override
^
1 mistakes
:react-native-orientation:compileReleaseJavaWithJavac FAILED
```

**Comment by andrerfneves** [comment]
Probably has to do with this: https://github.com/facebook/react-native/issues/15232

**Comment by Lizhooh** [comment]
@andrerfneves  After upgrading to V3.0, it has now been successful.
