### ISSUE TITLE
Screen orientation overrides previous screens

### ISSUE THREAD

**Issue by itswaze** [yamill/react-native-orientation#224]
Hi!
I have the navigation Screen A -> Screen B.
On Screen A I have `Orientation.lockToPortrait()`, and on Screen B I have `Orientation.unlockAllOrientations()`, but when I press to go back to screen A from screen B it overrides the `lockToPortrait` and unlocks all orientations.

How can I fix this?

**Comment by dotnetprofessional** [comment]
If you call <code>Orientation.unlockAllOrientations()</code> on screen B then you'll need to call <code>Orientation.lockToPortrait()</code> again when you navigate back to screen A. These methods are App wide, not to a specific screen.
