### ISSUE TITLE
Differentiate PORTRAIT with UPSIDEDOWN in addOrientationListener

### ISSUE THREAD

**Issue by pangers** [yamill/react-native-orientation#23]
As the title says. 

As I am creating my React Native app, I have different layouts shown to the user when the phone is in portrait and landscape. When I set 'unlockAllOrientations' for a particular screen I am seeing the expected layouts for portrait (home button at bottom) and landscape. However, when I rotate the phone upside down, the layout is completely mangled.

It is showing the portrait layout but with a 90 degree rotation (as if the app was in landscape) resulting in a buggy and ugly looking screen. I thought this might be a problem because in my XCode project I had unchecked the 'Upside Down' Device Orientation setting. So I turned it on and tried and again and I saw the same problem. My expected result was the portrait layout shown exactly as in the portrait orientation (with home button at bottom).

It looks like a react native app is prevented from being in the upside down orientation (can anyone confirm this?) whether or not the option is checked in XCode. After commenting out line 72 of RCTOrientation/Orientation.m my problem was instantly fixed.

As a result I propose to differentiate PORTRAIT with UPSIDEDOWN in addOrientationListener and anywhere else where it is appropriate in this library. 

What do you think @yamill ? I can make a pull request if you approve of this change.

**Comment by fr-kshibata** [comment]
I confirm this. I try to disable upside down in the xcode but still its overriden by react-native module http://stackoverflow.com/questions/22764255/disable-orientation-in-iphone-app-ios-7-xcode-5

**Comment by fr-kshibata** [comment]
Can we have a function just to disable portraitupsidedown? and not return it with portrait mode

**Comment by fr-kshibata** [comment]
For the meantime I edited Orientation.m

- (NSString *)getOrientationStr: (UIDeviceOrientation)orientation {
  NSString *orientationStr;
  switch (orientation) {
    case UIDeviceOrientationPortrait:
      orientationStr = @"PORTRAIT";
      break;
    case UIDeviceOrientationLandscapeLeft:
    case UIDeviceOrientationLandscapeRight:

      orientationStr = @"LANDSCAPE";
      break;
      
    case UIDeviceOrientationPortraitUpsideDown:
      orientationStr = @"PORTRAITUPSIDEDOWN";
      break;
      
    default:
      orientationStr = @"UNKNOWN";
      break;
  }
  return orientationStr;
}

**Comment by jpmerritt** [comment]
Can anyone confirm that it's not possible to render a react native view in true upside down orientation? 

react-native-orientation is setting UIInterfaceOrientationMaskAllButUpsideDown when you run Orientation.unlockAllOrientations(); which is not what I would expect. Is there a limitation from react-native itself?

**Comment by whizkid77** [comment]
I did have trouble with this a few weeks ago, but it works for me now.  In that time, I've upgraded to RN 0.20 though.  Upside down is enabled in Xcode, and all four orientations work in both simulator and a real iPad.

**Comment by noway** [comment]
I'm experiencing this on rn 0.62

**Comment by noway** [comment]
ok, fixed it with this patch:
```patch
diff --git a/node_modules/react-native-orientation/iOS/RCTOrientation/Orientation.m b/node_modules/react-native-orientation/iOS/RCTOrientation/Orientation.m
index 15e9927..2e07efd 100644
--- a/node_modules/react-native-orientation/iOS/RCTOrientation/Orientation.m
+++ b/node_modules/react-native-orientation/iOS/RCTOrientation/Orientation.m
@@ -12,7 +12,7 @@
 @implementation Orientation
 @synthesize bridge = _bridge;
 
-static UIInterfaceOrientationMask _orientation = UIInterfaceOrientationMaskAllButUpsideDown;
+static UIInterfaceOrientationMask _orientation = UIInterfaceOrientationMaskAll;
 + (void)setOrientation: (UIInterfaceOrientationMask)orientation {
   _orientation = orientation;
 }
@@ -218,7 +218,7 @@ - (NSString *)getSpecificOrientationStr: (UIDeviceOrientation)orientation {
   #if DEBUG
     NSLog(@"Unlock All Orientations");
   #endif
-  [Orientation setOrientation:UIInterfaceOrientationMaskAllButUpsideDown];
+  [Orientation setOrientation:UIInterfaceOrientationMaskAll];
 //  AppDelegate *delegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];
 //  delegate.orientation = 3;
 }
```
