### ISSUE TITLE
lockToPortrait not working on android

### ISSUE THREAD

**Issue by MrLoh** [yamill/react-native-orientation#231]
I got the library set up correctly and it works perfectly on iOS. But on android I do receive the events but the `lockToPortrait` doesn't work properly. I've checked that the android functions actually get called, but the orientation doesn't seem to get locked.

**Comment by stoneman1** [comment]
Do you have any code example which could be tested?

**Comment by MrLoh** [comment]
See my answer in #220 as well. I simply call the function during initialization of my app and then after my video player stops. All of that happens in side effects. The functions also arrive on the native side. I added a lot statement in java and the function of the library gets called. Am I miss understanding something about how the library works on android. I though I just call the function and then the orientation will lock.

**Comment by MrLoh** [comment]
Could it be, that the function can just take effect after a screen has properly been initialized on android?

**Comment by MrLoh** [comment]
Ok, it really seems like it had to do with the fact that screens weren't ready yet to receive the event or something like that. After firing events only when a screen was actually loaded it worked. It seems the screen locking on android might be more implemented on a per screen basis or something like that.

**Comment by zamponotiropita** [comment]
It doesn't work when testing on android. Also the solution above is not clear to me.
That's a simple example:

```jsx
import React, { Component } from 'react';
import { AppRegistry } from 'react-native';

import Root from 'src';

import Orientation from 'react-native-orientation';

Orientation.lockToPortrait();

export default class ReactNativeBaseProject extends Component {
  render() {
    return (
        <Root/>
    );
  }
};

AppRegistry.registerComponent('ReactNativeBaseProject', () => ReactNativeBaseProject);

```

**Comment by zamponotiropita** [comment]
@MrLoh what was your solution? Could you provide a code snippet?

**Comment by MrLoh** [comment]
Try using it in component did mount. Also to just fix the whole app orientation you should just configure your project correctly, instead of using this library.

**Comment by c-goettert** [comment]
@MrLoh do you have any suggestion on how to 'configure project correctly'? I think I have a similar scenario (Android): My whole App should be locked in Portrait except for one single View (Fullscreen Video-Player). 
As far as I know, you can only configure Screen-Orientation in `AndroidManifest.xml` for certain activities, but RN has only one activity right? How could you configure the orientation for your RN-Views? Is there a way to add a second activity which is configurable in `AndroidManifest.xml`?
Thanks you for your help! :)

**Comment by MrLoh** [comment]
@c-goettert You cannot easily create several activies without writing involved native code. Just use this library to lock the orientation in the componentDidMount of your screens

**Comment by amwebexpert** [comment]
Tried this which solvey the issue on our side:
```ts
  useOrientationChange(console.log);
. . .
  useEffect(() => {
    setTimeout(() => Orientation.lockToPortrait(), 10);
  }, []);
```
Even tried with a timeout of `0`ms instead of `10`ms and still fine. So deninitely a timing issue like the native Android `Activity` has to finish something before we call the _lock_ api call 🤔
