### ISSUE TITLE
function Orientation.getInitialOrientation() return same value 'PORTRAIT'

### ISSUE THREAD

**Issue by jiajiajiaga** [yamill/react-native-orientation#236]
hi, when i use the function Orientation.lockToLandscape(), screen rotate surely ,but the toast still in the left of screen, seeming the middle of Portrait , could you tell me the reason ..?

**Comment by andrerfneves** [comment]
@jiajiajiaga I'm going to need you to elaborate a little. Not sure what you mean by `the toast still in the left of screen`. Is there any code you can show, or repo that allows me to reproduce the issue?

**Comment by jiajiajiaga** [comment]
my problem is that toast's position is not in the center of screen in the model of Landscape,  it may be my toast lib's bug, thank u
