### ISSUE TITLE
ios: getting error with modal window: Exception thrown while executing UI block: Supported orientations has no common orientation with the application, and [RCTModalHostViewController shouldAutorate] is returning YES

### ISSUE THREAD

**Issue by vijay-dadhich09** [yamill/react-native-orientation#246]
I am getting following error when calling Orientation.lockToLandscape(); Any Solution?
Error:
Exception thrown while executing UI block: Supported orientations has no common orientation with the application, and [RCTModalHostViewController shouldAutorate] is returning YES

Code:
componentDidMount() {
    const initial = Orientation.getInitialOrientation();
    Orientation.unlockAllOrientations();
    if (initial === 'PORTRAIT') {
      console.log('Prtrate: ', initial);
      Orientation.lockToLandscape();
    } else {
      console.log('landscape: ', initial);
    }
  }

**Comment by vijay-dadhich09** [comment]
I found root cause of this issue. This is happening with modal window. My image view opening in the Modal Window and when I am changing from Portrait to landscape getting this error. Any solution?

**Comment by vijay-dadhich09** [comment]
found solution... Thanks
https://github.com/facebook/react-native/issues/11036

<Modal
        visible={true}
        supportedOrientations={['portrait', 'landscape']}
      >
      </Modal>

**Comment by tal987** [comment]
@vijay-dadhich09  where should I add this piece of code?

**Comment by indapublic** [comment]
@tal987 You should add props to your react-native modals

**Comment by indapublic** [comment]
https://facebook.github.io/react-native/docs/modal.html
