### ISSUE TITLE
[Android] Orientation.lockToPortrait(); locks orientation forever

### ISSUE THREAD

**Issue by nmorozov** [yamill/react-native-orientation#251]
Hi! I use this module on iOS and it works fine, but on Android I have one issue.

Steps to reproduce:
1. Create new application with create-react-native-app and eject it.
2. npm i react-native-orientation and do configuration step
3. react-native run-android and change orientation. Works properly.
4. Open App.js and add
```
  componentWillMount() {
    Orientation.lockToPortrait();
  }
```
5. react-native run-android and change orientation. Works properly.
6. Comment out
```
  //componentWillMount() {
    //Orientation.lockToPortrait();
  //}
```
7. react-native run-android and change orientation. Orientations is still locked to portrait
8. change componentWillMount method as following
```
  componentWillMount() {
    Orientation.UnlockAllOrientations();
  }
```
9. react-native run-android and change orientation. Orientations is still locked to portrait

Orientation can be unlocked only with app reinstallation.

```
    "react": "16.0.0",
    "react-native": "0.50.3"(test project)/"react-native": "^0.48.4"(production project),
    "react-native-orientation": "^3.1.0"
```

Devices:
Nexus 5X API 26 (emulator)
Honor Android 5.1.1 

What I'm doing wrong?

**Comment by nmorozov** [comment]
I have replaced
`activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);`
with
`activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR);`
here `android/src/main/java/com/github/yamill/orientation/OrientationModule.java:115` and now it works properly. is it a bug?

**Comment by hssrrw** [comment]
I have the same problem. Seems, @nmorozov's solution fixes it, thanks. Should there be a PR?

**Comment by stoneman1** [comment]
Yes sure you can make a PR and I will test it out. I am now trying to look at all the issues. Will make a new release today or maybe in January

**Comment by stoneman1** [comment]
Bug fixed and released.
