### ISSUE TITLE
iOS build failed on v3.1.2

### ISSUE THREAD

**Issue by wellyshen** [yamill/react-native-orientation#256]
I upgrade to v3.1.2 and update the `AppDelegate.m` file followed by **README** but it can't pass the iOS build. When I comment out the duplicated code, it become build success but the orientation is broke. Now I roll back to v3.1.0. Here's the screenshot of the failed part:

<img width="749" alt="2017-12-30 11 17 46" src="https://user-images.githubusercontent.com/21308003/34455332-e6614516-edb7-11e7-927d-ade98e58bef4.png">

**Comment by esutton** [comment]
Cannot run on iOS.

I had to roll back 3.1.2 to:
```
yarn add react-native-orientation@3.1.0
```

**Comment by stoneman1** [comment]
Ah probably something messed up in merging. So sorry. Will fix asap

**Comment by stoneman1** [comment]
There is now 3.1.3 released with fix
