### ISSUE TITLE
Orientation Events doesn't work when rotate device from "LANDSCAPE" to "PORTRAIT"

### ISSUE THREAD

**Issue by wellyshen** [yamill/react-native-orientation#260]
Hi I upgrade to v3.1.3 and I found the **Orientation Events** seems broke when rotate device from "LANDSCAPE" to "PORTRAIT". The "LANDSCAPE" event won't be triggered. Now I have to roll back to v3.1.0 again...

**Comment by stoneman1** [comment]
Which OS?

**Comment by wellyshen** [comment]
@stoneman1 iOS 11

**Comment by stoneman1** [comment]
Ok will test soon and try to fix.

**Comment by waquidvp** [comment]
I seem to have a similar issue where the Orientation event won't be triggered, it is always at portrait and doesn't change to Landscape. I have checked everywhere if I have locked the orientation, but it seems like I haven't and it is acting as if the orientation is locked. Also The same code works perfectly on Android. 

P.S. Before I added react-native-orientation, my app would automatically readjust to the orientation.

**Comment by stoneman1** [comment]
Any errors? Seems to be working for me?

**Comment by lukewlms** [comment]
Same issue - with the default recommended code, my app is always locked to Portrait.

By using @wellyshen's change I'm able to get the locking to work as expected.

**Comment by stoneman1** [comment]
@wellyshen thanks for the info. So the problem was in README. Will fix the readme asap 👍  The demo had it correct.

**Comment by stoneman1** [comment]
Thanks again. Now it is fixed in #261
