### ISSUE TITLE
After rotation Dimensions remain the same

### ISSUE THREAD

**Issue by navy1978** [yamill/react-native-orientation#3]
Hi The dimension of the page is not affected by the rotation,  so for example calling this in Landscape:
Dimensions.get('window').height has the same result of calling it in Portrait

**Comment by yamill** [comment]
@navy1978 this is because the Dimensions module doesn't update when the orientation changes. I think the RN team is working on this to make it better.

**Comment by unknownexception** [comment]
As a temporary solution: 

```
RCT_EXPORT_METHOD(getDimensions:(RCTResponseSenderBlock)callback)
{
  UIViewController *root = [[[[UIApplication sharedApplication] delegate] window] rootViewController];

  NSDictionary *dimensions = @{
                               @"window": @{
                                   @"width": @(root.view.frame.size.width),
                                   @"height": @(root.view.frame.size.height)
                               }
  };
 
  callback(@[[NSNull null], dimensions]);
}
```

Of course, no more `Dimensions` module, window sizes become part of the global state and should be passed via properties.

**Comment by yamill** [comment]
You can use the onLayout event to resolve this issue. I will close this issue now.

**Comment by hamidjafari** [comment]
i've use this code to get the correct height/width after rotation.

`onLayout(evt){`
`      var height = evt.nativeEvent.layout.height;  `
`      var width = evt.nativeEvent.layout.width;  `
` // do something with these values...`
`}`
