### ISSUE TITLE
Android release got failed.

### ISSUE THREAD

**Issue by Nics08** [yamill/react-native-orientation#325]
Hello There,

In React Native my android release build got failed because of below error, can you please help me out i need to upload application in play store.

* What went wrong:
Execution failed for task ':react-native-orientation:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

build.gradle ==>>
ext {
    minSdkVersion = 16
    compileSdkVersion = 27
    targetSdkVersion = 26
    supportLibVersion = "26.1.0"
}

package.json
"dependencies": {
    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-orientation": "^3.1.3",
 },

**Comment by Nics08** [comment]
I have solved issue with below code in android/build.gradle, might someone helps.

subprojects {
  project.configurations.all {
      afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 26
                buildToolsVersion '26.0.2'
            }
        }
    }
     resolutionStrategy.eachDependency { details ->
        if (details.requested.group == 'com.android.support'
              && !details.requested.name.contains('multidex') ) {
           details.useVersion "26.0.2"
        }
     }
  }
}

**Comment by paritosh-yadav** [comment]
Its because mismatch versions in this projects build configuration and the app level build configurations.

I solved it with the following changes:

`def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion safeExtGet('compileSdkVersion', 28)
    buildToolsVersion safeExtGet('buildToolsVersion', '28.0.3')

    defaultConfig {
        minSdkVersion safeExtGet('minSdkVersion', 19)
        targetSdkVersion safeExtGet('targetSdkVersion', 28)
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
}

dependencies {
    compile "com.facebook.react:react-native:+"
}
`
