### ISSUE TITLE
addOrientationListener not working/getting called

### ISSUE THREAD

**Issue by MrEdinLaw** [yamill/react-native-orientation#326]
I followed the tutorial about installing it and the usage.
The initial orientation seems to work but the listener doesnt.

**Comment by jayeshanandani** [comment]
I can reproduce that.

**Comment by felixus95** [comment]
+1 on iOS 12. If you need more Info, please tell us what is needed. :)

**Comment by retyui** [comment]
This repo dead , use the fork https://github.com/wonday/react-native-orientation-locker

**Comment by MrEdinLaw** [comment]
> This repo dead , use the fork https://github.com/wonday/react-native-orientation-locker

Finally a soultion, thank you very much!
