### ISSUE TITLE
Locking to Portrait on app launching rotates from Landscape to Portrait (iOS)

### ISSUE THREAD

**Issue by vladinko0** [yamill/react-native-orientation#331]
I want to lock the orientation of the first screen of app to Portrait. But when I launch the application I see for a while landscape orientation and then quickly rotating to the Portrait orientation. Next screens are okey.

Here is my code:
```
componentDidMount() {
        Orientation.lockToPortrait();
    }
```

Is it possible to solve this performance issue?

**Comment by retyui** [comment]
This repo dead , use the fork https://github.com/wonday/react-native-orientation-locker

**Comment by vladinko0** [comment]
It was my error.
I used in one class redundant code:

 ```
   const setLandscapeRightOrientation = Platform.select({
        ios: Orientation.lockToLandscapeRight(),
        android: Orientation.lockToLandscapeLeft(),
    });
```
