### ISSUE TITLE
Execution failed for task ':react-native-image-crop-picker:verifyReleaseResources'.

### ISSUE THREAD

**Issue by yqyily** [yamill/react-native-orientation#333]
react-native:0.57.2
react:16.5.0
react-native-orientation:3.1.3
--------------------------------------------
when i build app,Build failed with an exception.
`
error: invalid file path '/home/kf/Documents/kunfei_app/node_modules/react-native-image-crop-picker/android/build/intermediates/manifests/aapt/release/AndroidManifest.xml'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-crop-picker:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: AAPT2 error: check logs for details
`

`
"dependencies": {
    "babel-preset-react-native": "^2.1.0",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "prop-types": "^15.6.2",
    "react": "16.5.0",
    "react-native": "0.57.2",
    "react-native-baidumap-sdk": "^0.6.0",
    "react-native-calendars": "^1.21.0",
    "react-native-charts-wrapper": "^0.5.0",
    "react-native-easy-toast": "^1.1.0",
    "react-native-elements": "^1.0.0-beta7",
    "react-native-image-crop-picker": "^0.21.3",
    "react-native-modal": "^7.0.0",
    "react-native-orientation": "^3.1.3",
    "react-native-shadow": "^1.2.2",
    "react-native-svg": "^8.0.8",
    "react-native-vector-icons": "^6.0.2",
    "react-navigation": "^2.17.0"
  },
/android/build.gradle
buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url 'https://maven.google.com' }
        maven { url "https://jitpack.io" }
        google()
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}
`

**Comment by retyui** [comment]
https://github.com/yamill/react-native-orientation/issues/343
