### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_Orientation

### ISSUE THREAD

**Issue by ogerfaber** [yamill/react-native-orientation#363]
After installing and linking project following the readme instructions. Xcode still do not find `Orientation.h`, so I added `$(SRCROOT)/../node_modules/react-native-orientation/iOS/RCTOrientation` recursive in `Header Search Paths` and then I'm getting the following build error: `Undefined symbol: _OBJC_CLASS_$_Orientation`

My React Native version is 0.60.3

<img width="1135" alt="Capture d’écran 2019-09-25 à 17 56 07" src="https://user-images.githubusercontent.com/47740432/65617923-c6490d00-dfbd-11e9-8ad2-0dc71b91fdea.png">

**Comment by pans0911** [comment]
then you resolve this question?

**Comment by ogerfaber** [comment]
no sorry

**Comment by hossamnasser938** [comment]
experiencing the same issue

**Comment by appfr3d** [comment]
Any progress on this? I am encountering the same issue now.

**Comment by appfr3d** [comment]
A bit late, but someone still encounters this error.
I fixed this by adding this line to my Podfile:
`pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'`
and doing a `pod install` inside the ios folder in my terminal.
