### ISSUE TITLE
Unbalanced calls start/end for tag 5

### ISSUE THREAD

**Issue by latusaki** [yamill/react-native-orientation#37]
I am getting the above message when Debugging in Chrome. Comes from RCTLog.js:38.

I am using react native 0.18.1 

Is this something to look at or safe to ignore? I believe there is an 'info' icon next to the message (blue circle with white line)

**Comment by yamill** [comment]
I see the same. I think it's safe to ignore right now. I have my app running in production and haven't experience any issues.

I'll close this for now. Thanks.
