### ISSUE TITLE
Landscape Left is not supported

### ISSUE THREAD

**Issue by manask88** [yamill/react-native-orientation#38]
After the latest update where an orientation change is forced there is one unintended consequence. whenever landscape is forced, it will be in landscape-right. This might be ok for some apps but for our use case it breaks.  Is there a way to get around this? if not, would you be willing to take a PR which solves this problem?
my idea is to have the following orientations after the change:

LANDSCAPE
LANDSCAPE-LEFT (new)
PORTRAIT
UNKNOWN
PORTRAITUPSIDEDOWN
PORTRAIT

**Comment by yamill** [comment]
I'm open to someone opening a PR for this.

**Comment by yamill** [comment]
A PR was submitted for this @manask88. I'll be closing this.

**Comment by manask88** [comment]
great, thanks!
