### ISSUE TITLE
 Could not determine the dependencies of task ':react-native-orientation:compileDebugAidl'. 

### ISSUE THREAD

**Issue by Liqiankun** [yamill/react-native-orientation#386]
### Log
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-orientation:compileDebugAidl'.
> Failed to find Platform SDK with path: platforms;android-23

### React native info
System:
OS: macOS 10.15.5
CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
Memory: 178.86 MB / 8.00 GB
Shell: 5.8 - /usr/local/bin/zsh
Binaries:
Node: 10.15.3 - /usr/local/bin/node
Yarn: 1.21.1 - /usr/local/bin/yarn
npm: 6.4.1 - /usr/local/bin/npm
Watchman: 4.9.0 - /usr/local/bin/watchman
Managers:
CocoaPods: 1.9.1 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
Android SDK:
API Levels: 28, 29
Build Tools: 28.0.3, 29.0.3
System Images: android-28 | Intel x86 Atom_64
Android NDK: Not Found
IDEs:
Android Studio: 4.0 AI-193.6911.18.40.6514223
Xcode: 11.6/11E708 - /usr/bin/xcodebuild
Languages:
Java: 1.8.0_251 - /usr/bin/javac
Python: 2.7.16 - /usr/bin/python
npmPackages:
@react-native-community/cli: Not Found
react: 16.11.0 => 16.11.0
react-native: 0.62.2 => 0.62.2
npmGlobalPackages:
react-native: Not Found

**Comment by mafaqriaz** [comment]
navigate to node-modules/react-native-orientation/android/build.gradle and change this file as below:

`defaultConfig {
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }`

**Comment by Liqiankun** [comment]
@mafaqriaz Let me try it out
