### ISSUE TITLE
"Unable to resolve module NativeModules"

### ISSUE THREAD

**Issue by tnguyen42** [yamill/react-native-orientation#4]
Hi guys,

I've got an error displayed in the terminal when I run the app. It says:
```
Unable to resolve module NativeModules from /App/node_modules/react-native-orientation/index.js
Unable to resolve module RCTDeviceEventEmitter from /App/node_modules/react-native-orientation/index.js
```

However the project works correctly. Any idea what could cause this?

**Comment by yamill** [comment]
I'm having the same issue. I'll take a look

**Comment by tnguyen42** [comment]
Apparently many plugins encounter dependency issues since the 0.9 release.
Thanks for having a look :-)

**Comment by yamill** [comment]
Pushed the fix to git, thanks for catching this:
https://github.com/yamill/react-native-orientation/blob/master/index.js

**Comment by tnguyen42** [comment]
Npm Check Update doesn't detect any update. Should I update it manually?

**Comment by yamill** [comment]
You can try now. Just bumped the version :+1:

**Comment by tnguyen42** [comment]
Works fine. Cheers mate!
