### ISSUE TITLE
Get current lock

### ISSUE THREAD

**Issue by RyGuyM** [yamill/react-native-orientation#40]
Is there a way to get the current orientation lock? I have some conditionals that change what is displayed based on whether the view is unlocked in landscape mode or not.

**Comment by yamill** [comment]
It can probably get exposed the same way we listen to Orientation changes. I would submit a PR but I'm really busy these days. I'm open for anyone to take this on.

**Comment by andrerfneves** [comment]
@RyGuyM  couldn't you simply use a state variable for this conditional along with the orientation listener?

**Comment by andrerfneves** [comment]
Closing this for now. Open a new issue if it persists.
