### ISSUE TITLE
undefined is not an object (evaluating 'Orientation.lockToPortrait')

### ISSUE THREAD

**Issue by bpolonia** [yamill/react-native-orientation#43]
Hi I am trying to use the lockToPortrait function and I keep get this error in console: 

> undefined is not an object (evaluating 'Orientation.lockToPortrait')

I imported your package, set its name to Orientation just as in your usage examples, and inside of `componentDidMount` I am just calling `Orientation.lockToPortrait();`

Please help :)

**Comment by yamill** [comment]
Did you import the files in xcode?

**Comment by bpolonia** [comment]
Yes I did. I right clicked on my project name, selected **Add Files to <My Project Name>** I selected **RCTOrientation** from node_module/react-native-orientation/ 

The only thing I didn't see was an option to have **Create Groups** selected.

Here is what it looks like.

![screen shot 2016-02-10 at 4 36 10 pm](https://cloud.githubusercontent.com/assets/6245672/12962711/949a2fb2-d014-11e5-82cc-9a30274fa016.png)

**Comment by nurdeen** [comment]
@bpolonia after you click on "Add Files to Project Name" there is a button called "Options" on the screen where you select the file(s). "Create Groups" is there.

**Comment by bpolonia** [comment]
@nurdeen Thank you! That worked. :+1:

**Comment by courthead** [comment]
@bpolonia  I'm having the same error appear when I run my project on Android. I followed all of the instructions in the README. Any ideas?

**Comment by mvayngrib** [comment]
@yamill this seems to be a recurrent issue for me. Any idea why I would have to rebuild periodically? I think it happens especially often when I switch from debugging the iOS simulator to debugging the android emulator and vice versa

**Comment by mvayngrib** [comment]
nm, seems it has been fixed in #85. Could you republish the module to npm?

**Comment by jctadios** [comment]
same problem here but I'm using expo. Any idea?

**Comment by andrerfneves** [comment]
@jctadios you cannot use this with Expo. You'll have to `eject` from your Expo build to be able to write native code, and thus integrate this package. Please refrain from commenting on closed tickets. Create a new one if you'd like further help/clarification.
