### ISSUE TITLE
Install with rnpm

### ISSUE THREAD

**Issue by jimthedev** [yamill/react-native-orientation#45]
Hi there,

Is it possible to install this with rnpm instead of doing it manually?

Cheers.

**Comment by yamill** [comment]
You can always install with npm :)

I'm open for an rnpm PR though.

**Comment by jimthedev** [comment]
Sorry, I realize I misunderstood. Closing :)

**Comment by SudoPlz** [comment]
So can we install using rnpm at the moment?
