### ISSUE TITLE
Incomplete module bridging on Android

### ISSUE THREAD

**Issue by clmntcrl** [yamill/react-native-orientation#48]
Those functions are not bridged for Android:
- `getSpecificOrientation(function(err, specificOrientation))`
- `lockToLandscapeLeft()`
- `lockToLandscapeRight()`

**Comment by clmntcrl** [comment]
As a workaround you could:

- call `lockToLandscape()` on `lockToLandscapeLeft()` and `lockToLandscapeRight() `,
- call `getOrientation()` on `getSpecificOrientation() ` and return `"LANDSCAPE-LEFT"` (or `"LANDSCAPE-RIGHT"`) when `getOrientation()` return `"LANDSCAPE"`.

In that way, all exposed functions have an implementation on both Android an iOS.

---

I have also find this [http://stackoverflow.com/a/10383164/1356584](http://stackoverflow.com/a/10383164/1356584) to get specific orientation but I'm not used to work on Android and don't know if it works for all Android devices and versions.

**Comment by yamill** [comment]
@clmntcrl a new PR was submitted for this - https://github.com/yamill/react-native-orientation/pull/51

Thanks to @scgough
