### ISSUE TITLE
Podspecs

### ISSUE THREAD

**Issue by ajoshdee** [yamill/react-native-orientation#49]
Hi can u make podspecs for this?

**Comment by markrickert** [comment]
Hey @ajoshdee, a podspec can not be made for this project since it's react-native and not swift/objective-c. You should use `npm` to install this into your react native project. https://facebook.github.io/react-native/docs/getting-started.html

**Comment by ajoshdee** [comment]
i mean for the .m and .h file so i won't have to import it manually
