### ISSUE TITLE
Switching screen orientation

### ISSUE THREAD

**Issue by ajoshdee** [yamill/react-native-orientation#52]
Hi, I'm switching to landscape orientation and back to portrait using the lockTo function. How do i do this? I keep getting an error when i set it on "componentWillUnmount" 
`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.`

**Comment by masterkrang** [comment]
@ajoshdee did you have any luck figuring out why this is being caused? Same thing here, I'm calling this way:
```
  componentDidMount() {
    Orientation.addOrientationListener(this.orientationDidChange.bind(this));
  }
  orientationDidChange(orientation) {
    this.setState({
      orientation: orientation
    });
  }
```

Same error: 

```
ExceptionsManager.js:76 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.
```

cc @yamill

**Comment by ajoshdee** [comment]
I'm not using this anymore , but my best bet is using 
```
InteractionManager.runAfterInteractions(() => {
    //YOUR ORIENTATION HERE
    });
```

**Comment by colinramsay** [comment]
I can confirm what @ajoshdee says:

```
    Orientation.lockToPortrait()
    InteractionManager.runAfterInteractions(() => {
      // work with this.setState
    })
```

**Comment by saidmoya12** [comment]
Use Orientation.unlockAllOrientations() instance of setState.

React component state only work for mountent components

if problem persist use
```js
setTimeout(()=>{
//do something.
}, 100)
```
