### ISSUE TITLE
Wrong Orientation on iOS

### ISSUE THREAD

**Issue by venk-aw** [yamill/react-native-orientation#56]
Orientation is identified as UNKNOWN when device is laid on a flat surface.

**Comment by venk-aw** [comment]
You can use UIInterfaceOrientation instead of UIDeviceOrientation. 
Look at following URL http://stackoverflow.com/questions/3901337/ipad-launch-orientation-when-flat-on-surface

**Comment by stereodenis** [comment]
@venk-aw look at https://github.com/yamill/react-native-orientation/issues/78

**Comment by alizbazar** [comment]
Agree with @venk-aw . What most people care is InterfaceOrientation, i.e. how contents of the screen has to be adjusted to accommodate the new orientation that is being displayed (not the orientation that user happens to hold his device on).

Even if #78 was implemented, you'd still wouldn't know what to render - portrait or landscape - when getting FACEDOWN or FACEUP.

**Comment by andrerfneves** [comment]
This is an iOS-specific issue. PRs are welcome.
