### ISSUE TITLE
listener can get called with a meaningless value

### ISSUE THREAD

**Issue by chetstone** [yamill/react-native-orientation#58]
It seems whenever orientation changes, my listener gets called twice: once with a valid string, then with an integer:

> 2016-04-05 17:30:22.047 browser.js:107 History:debug Window width +7ms 480
> 2016-04-05 17:30:22.054 browser.js:107 History:debug New Device Orientation:  +7ms LANDSCAPE
> 2016-04-05 17:30:22.055 browser.js:107 History:debug New Device Orientation:  +1ms 3
> 2016-04-05 17:30:44.438 browser.js:107 History:debug Window width +2ms 320
> 2016-04-05 17:30:44.446 browser.js:107 History:debug New Device Orientation:  +8ms PORTRAIT
> 2016-04-05 17:30:44.446 browser.js:107 History:debug New Device Orientation:  +0ms 1

Workaround: test if the parameter is one of the expected strings, otherwise ignore it.

**Comment by andrerfneves** [comment]
More info needed. Please open a new issue if this is persisting for you. Also try and update the package since there have been multiple updates. Refer to README.
