### ISSUE TITLE
RCTEventDeviceEmitter - unable to resolve module

### ISSUE THREAD

**Issue by tnguyen42** [yamill/react-native-orientation#6]
Hey,
Working on 1.6.0 here. Works fine for my use (lockToPortrait only), but when I run the app, I still got the error:
```
Unable to resolve module RCTDeviceEventEmitter from /Users/tnguyen/JibberJabber/JibberJabber/node_modules/react-native-orientation/index.js
```
Works better if I comment `//var RCTDeviceEventEmitter = require('RCTDeviceEventEmitter');` in index.js, but I don't know if there will be any problem then.

**Comment by tnguyen42** [comment]
Hi @yamill,
Still no fix?

**Comment by watert** [comment]
maybe its because the version of react-native in your npm is too old?

**Comment by tnguyen42** [comment]
Actually, it's become kind of a mess since RN 0.11, so I'm waiting for things to calm down a little... Right now I can't get anything compiled anymore, but it's probably not RN-orientation's fault.

**Comment by chetstone** [comment]
I'm seeing this error and reverting commit ce56ce656cc4d60cdc08fba0ad6965ef5ebd74cd makes it go away.

**Comment by yamill** [comment]
@chetstone mind pushing a PR for this? :)

**Comment by yamill** [comment]
Thanks!
