### ISSUE TITLE
Get orientation change when orientation is locked

### ISSUE THREAD

**Issue by stereodenis** [yamill/react-native-orientation#63]
Is there a way to get orientation, when orientation is locked?

for example:
Orientation.lockToPortrait()

but when device get landscape orientation — I want to get this event

**Comment by sooth-sayer** [comment]
@stereodenis In the latest version (1.17.0) I see that the orientation listener and the specific orientation listener are called, regardless of orientation lock.

**Comment by ultimagriever** [comment]
It doesn't on Android.

**Comment by andrerfneves** [comment]
Please try updated v2.0.0 as well as updated guide on README. Listeners should get called even when View is locked.
