### ISSUE TITLE
lockToLandscapeRight and lockToLandscapeLeft are swapped

### ISSUE THREAD

**Issue by PublicParadise** [yamill/react-native-orientation#65]
See https://github.com/yamill/react-native-orientation/blob/master/RCTOrientation/Orientation.m#L144-L152

``` objective-c
RCT_EXPORT_METHOD(lockToLandscapeRight)
...
setValue:[NSNumber numberWithInteger: UIInterfaceOrientationLandscapeLeft]
```

versus https://github.com/yamill/react-native-orientation/blob/master/RCTOrientation/Orientation.m#L156-L165

``` objective-c
RCT_EXPORT_METHOD(lockToLandscapeLeft)
...
setValue:[NSNumber numberWithInteger: UIInterfaceOrientationLandscapeRight]
```

**Comment by Sh3rawi** [comment]
Can you confirm that its swapped on a real device ? Unfortunately i do not have an access to an iPhone these couple of days. 
However, I wrote this by trial => i rotated the device to one of the 2 sides, and after that I called the lockToLandscape.What should happen is that it should not re-rotate to the other side, which confirmed to me this was right.
Can you try that out and tell me what happens ?

**Comment by gethinwebster** [comment]
@Sh3rawi I've just come across this issue, and can confirm that it's a bug: if you check the device orientation, and then apply the 'matching' `lockToLandscape*` method, it will flip the orientation when locking it.

**Comment by Sh3rawi** [comment]
@gethinwebster can you provide a gif or a video to demonstrate it? I've checked it now.
But let me get this straight, you mean if you are already in landscape mode and you lock it, it will flip to the other landscape direction, right ?

**Comment by eduardinni** [comment]
I confirm that the methods are swapped, looking at the native code looks is obvious there's a bug. I've opened a pull request #122

**Comment by andrerfneves** [comment]
Resolved and merged.
