### ISSUE TITLE
Does it override xcode settings?

### ISSUE THREAD

**Issue by dwaligora** [yamill/react-native-orientation#68]
Hey guys,

Does this lib override the default project settings set in xcode? I am experiencing really wired behaviour after adding the lib into my project.

It is locked to the `portrait` orientation but when I add this lib (and I even dont import it anywhere in my source code) it overrides the orientation setting and unlocks all. Is it how it supposed to behave?

What I am trying to achieve is to enable only for 1 view (with video obviously ... ) the landscape orientation? Is it possible and I am doing something wrong? 

Thanks for your help guys!

**Comment by swaroopa94** [comment]
Hey Why you closed the issue did you solve it
Can you tell me how did you solve it

**Comment by DannyvanderJagt** [comment]
We experienced the same, just for the record: Does anyone know if this package override xcode settings and why it does not respect it?
