### ISSUE TITLE
Can't use module from an InputMethodService on Android

### ISSUE THREAD

**Issue by skilesare** [yamill/react-native-orientation#70]
I'm trying to use the orientation package from an InputMethodService to force my React-Native componet to rerender.   Basically I need to recalclate the style and apply the different width to the width of my controls.  Unfortuantely the orientation module on android requires an activity in the constructor. 

`new OrientationPackage(Activity activity)`

 Any ideas on how to pass it something Activy like to the constructor?  Or maybe an alternate constructor that takes an InputMethodService?  Or better yet, an empty construtor that grabs onto what it needs in the constructor via some sort of global singleton?

**Comment by webmakersteve** [comment]
Bump. Having this issue as well.

**Comment by andrerfneves** [comment]
@skilesare and @webmakersteve After RN 0.29 the constructors for Android changed. Could you test with latest updates?

**Comment by andrerfneves** [comment]
Closing this for now.
