### ISSUE TITLE
RN 0.11 Conflicting return type in AppDelegate.m

### ISSUE THREAD

**Issue by tnguyen42** [yamill/react-native-orientation#8]
Hi,

Since RN 0.11, the Installation instructions may be out of date. In particularly, this line gets a warning for a conflicting return type in AppDelegate.m:

`- (NSUInteger)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *) window {`

**Comment by yamill** [comment]
I believe this is resolved. I'll close this.
