### ISSUE TITLE
iOS 6s+

### ISSUE THREAD

**Issue by toddmetheny** [yamill/react-native-orientation#81]
I'm using react-native-orientation and it works great on my iphone 6s. It doesn't seem to recognize events consistently on ios 6s-plus, though. 

I wanted to check to see if this is an implementation error on my part or an issue. Have people been successfully using this library with 6s-plus? Was that included in testing? Thanks in advance.

**Comment by colinramsay** [comment]
I think we need more information @toddmetheny - were you able to resolve this or do you still have an issue?

**Comment by andrerfneves** [comment]
Closing this as it's been opened for over a year and the actual iOS device type shouldn't matter. @toddmetheny please try with the latest package version (check README for more info)

**Comment by marlti7** [comment]
i face the same problem. just in 6s-plus
