### ISSUE TITLE
RN 0.29 installation guide change

### ISSUE THREAD

**Issue by stereodenis** [yamill/react-native-orientation#83]
https://github.com/facebook/react-native/releases/tag/v0.29.0-rc.0

**Comment by philikon** [comment]
Yeah, so, RN 0.29 moves the module instantiation from the Activity to the Application. react-native-orientation currently depends on getting a reference of the activity passed in...

**Comment by SudoPlz** [comment]
So what do we pass to `new OrientationPackage(this),` ?

**Comment by esutton** [comment]
In general, how can you pass the activity to a package from within ReactApplication::getPackages() in the MainApplication.java ?
