### ISSUE TITLE
Error:Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by riten7** [yamill/react-native-orientation#84]
When I put this line 
    `compile project(':react-native-orientation')` in dependencies section of gradle file then this error occurs. If removed build is successful but Orientation change cannot be imported in the activity..What am I missing?

**Comment by stereodenis** [comment]
@riten7 got this, when run `rnpm link`
but I have 
`compile project(':Orientation')`

**Comment by riten7** [comment]
Do I need to use npm install ... process and then npm link ???

**Comment by andrerfneves** [comment]
Please use the latest version of the package and follow the README for updated guide on how to install and link native dependencies for both Android and iOS platforms
