### ISSUE TITLE
Bluetooth permission

### ISSUE THREAD

**Issue by jwarby** [yamill/react-native-orientation#86]
I noticed that after I included this module, my app was using bluetooth permissions.  I had a quick look through this repo and the only reference I can find to bluetooth is the `<uses-permission />` tag in `AndroidManfiest.xml`.

I was able to remove the permission from my app by putting `<uses-permission android:name="android.permission.BLUETOOTH" tools:node="remove" />` in my app's `AndroidManifest.xml`, and everything still works fine, so is this permission really needed or should it be removed from this module?

**Comment by lovato** [comment]
Noticed the same today... Will do the same as @jwarby

**Comment by andrerfneves** [comment]
v2.0.0 resolves this. Please update. Cheers
