### ISSUE TITLE
Installing on Android via rnpm does not seem to work.

### ISSUE THREAD

**Issue by marktolson** [yamill/react-native-orientation#87]
Receiving undefined is not an object whenever calling Orientation.initialOrientation.

**Comment by larilampen** [comment]
It works with react-native versions below 0.29 only, a symptom of a breaking change in the application template. Pull request #85 fixes the issue, so either use the code in that or (if you can afford to) wait until it is merged and released.

**Comment by andrerfneves** [comment]
Please follow updated README documentation on installing this package. If problems persist, create a new issue. Works with latest RN 0.44
