### ISSUE TITLE
orientation.h file is not found

### ISSUE THREAD

**Issue by shaikhussian** [yamill/react-native-orientation#91]
Getting an error like  orientation.h file is not found, when i try to run it in xcode, please give me suggestion that how to solve this

**Comment by tststs** [comment]
same issue with react-native@0.31

**Comment by tststs** [comment]
don't know what caused the issue, but it appeared after upgrading to `react-native@0.31`

you can use:

`#import "../../node_modules/react-native-orientation/iOS/RCTOrientation/Orientation.h"`

as a temporary workaround.

**Comment by lzm8607** [comment]
libRCTOrientation.a can't be created..

**Comment by mjbader** [comment]
For anyone still encountering this issue, I fixed it by manually linking the library.  Step 3 was the step I overlooked.

http://facebook.github.io/react-native/docs/linking-libraries-ios.html#step-3

**Comment by leechance** [comment]
`react-native link` at the home directory of your project

**Comment by jiteshwadia** [comment]
Tried options suggested by, @tststs , @mjbader and @leechance. 

@mjbader Can you let us know what is the exact path you entered in `Xcode->Header path`.
Mine is: `$(SRCROOT)/node_modules/react-native-orientation/iOS/RCTOrientation/`

@leechance  link is already done.

But xCode still gives file not found error.

**Comment by mjbader** [comment]
@jiteshwadia MY header search path is 
$(SRCROOT)/../node_modules/react-native-orientation/iOS/RCTOrientation

**Comment by andrerfneves** [comment]
Please follow updated README documentation on installing this package. If problems persist, create a new issue.
