### ISSUE TITLE
Add support for react-native > 0.29.0

### ISSUE THREAD

**Issue by agrcrobles** [yamill/react-native-orientation#93]
The following code is no longer valid in new versions from react-native 0.29.0

```
import com.github.yamill.orientation.OrientationPackage;  // <--- import

public class MainActivity extends ReactActivity {
  ......

  @Override
  protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new OrientationPackage(this)      <------- Add this
      );
  }

  ......

}
```

That is because `this` scope is `Application` instead of an activity.

**Comment by aboutqx** [comment]
Actually the code in github may works,it needs to be submitted to npm.

**Comment by magicspon** [comment]
The current instructions are not working for me (using the latest version of react-native)

**Comment by esutton** [comment]
@aboutqx Thank you!

```
    "react": "^15.3.1",
    "react-native": "^0.32.0",

    "react-native-orientation": "git+https://github.com/yamill/react-native-orientation", 
```

**Comment by esutton** [comment]
Works fine on iOS. Something broken on Android. ( Android 6.0.1 and RN 0.33 )
https://github.com/yamill/react-native-orientation/issues/100  [Orientation not changing on Android 6.0.1](https://github.com/yamill/react-native-orientation/issues/100)

**Comment by philikon** [comment]
@yamill can you push another release to npmjs.com please?

**Comment by liutian1937** [comment]
+1

**Comment by idlework** [comment]
+1

**Comment by annelorraineuy** [comment]
+1

**Comment by codetony25** [comment]
+1

**Comment by ostigley** [comment]
+1

**Comment by NickKotowski** [comment]
+1

**Comment by loehnertz** [comment]
+1

**Comment by Matus-Stastny** [comment]
+1

**Comment by andrerfneves** [comment]
2.0 version of this will be published to NPM as soon as it's release-ready. Please follow the updates through on #174.
