### ISSUE TITLE
[HELP] Fixed landscape mod

### ISSUE THREAD

**Issue by flaviotobi** [yamill/react-native-orientation#99]
i'm trying to fix one of many views in landscape.
But unfortunately  when i rotate the device, the screen go back to portrait.
I'm using :
     Orientation.lockToLandscapeLeft();

and have tried with: 
 Orientation.lockToPortrait();

React-Native: 0.31.0
Running app in iPhone 6s

**Comment by flaviotobi** [comment]
solved

**Comment by noxowe** [comment]
@flaviotobi do you mind sharing how? I have the same problem

**Comment by flaviotobi** [comment]
@noxowe  Hi there :) by the way this method is not original mine, i saw this from someone issue in this package. 

1- download the master from git hub (dont do npm install, it's buggy )
2- put the master in project folder node_modules
3- link the library 
4- try it out =D

In point 3 you should go to the docs of this package and see what you have to do
(if i remember correctly is just link the package and add a few lines of code in iOS and other ones in Android.)


code that i use: 
```
componentDidMount= () => {
    Orientation.unlockAllOrientations();
    Orientation.lockToLandscapeLeft(); //this will lock the view to Landscape
  }

  componentWillUnmount= () => {
    Orientation.unlockAllOrientations();
    Orientation.lockToPortrait(); //this will lock the view to Portrait
  }
```
